### ISSUE TITLE
Don't ever use refresh() in your FooController which extends GetxController

### ISSUE THREAD

**Issue by ad-on-is** [jonataslaw/getx#1016]
I just lost hours of time, when I implemented a `refresh()` function in my `FooController`.

```dart
FooController extends GetxController {
Future<void> refresh() {...}
}
```

Since `GetxController` has the same function (which I didn't know), my code got stuck in a loop.
So, for your time's sake, don't make the same mistake as I did :-)

**Comment by jonataslaw** [comment]
Yes, there is this function in ListNotifier.
I recommend everyone to use a Linter, this would not be possible if there was a Linter, since you would need to override the inherited method, and this would be marked with a warning
![image](https://user-images.githubusercontent.com/35742643/104775721-95af5880-5757-11eb-9797-6f22846e40ad.png)

**Comment by ad-on-is** [comment]
@jonataslaw Thank you! I newer knew, there was a linting-file provided by the Flutter team, which would've helped me.
I always used the linting of the VS Code extension.
For anyone else out there, just put this file into your project-root: https://raw.githubusercontent.com/flutter/flutter/master/analysis_options.yaml
