### ISSUE TITLE
How to use global route redirection？

### ISSUE THREAD

**Issue by qcks** [jonataslaw/getx#1115]
Before using GetX, I intercepted routes.
```
Route onGenerateRoute(RouteSettings settings) {
    .....
    var route;
    if (!isLoging)
       return LoginRoute;
    return route;
  }
```
onGenerateRoute: (getPages != null ? generator : onGenerateRoute),//GetX

What does PageRedirect do? How do I use it?

Please open the "generator" method, there will be many people who need to modify it.

GetPage ->middlewares  is not convenient

**Comment by jonataslaw** [comment]
Using a global setting is terrible, you prevent a page from being treated specifically. Inserting your logic on onGenerateRoute is  scary. You understand a code does not mean that other developers will understand it.
If you need to get the data somewhere and treat it, and you have another 300 different treatments, will you insert everything into onGenerateRoute? Sorry, but I can't see it as a possible alternative, I may be being opinionated about it, but this is just terrible from the perspective of project architecture.
Using Middlewares is the most convenient and minimally maintainable way that a developer can go through to modify the browsing behavior.

If you need the page to have a redirect, you add that Middleware, otherwise, don't add it, you can reuse the Middleware on any page, and thus create defined rules for each one.

You can add the following redirect to a file that extends GetMiddleware:

GetPage redirect () => isLogged? null: RouteSettings (name: '/ login');

And ready.

**Comment by qcks** [comment]
> Using a global setting is terrible, you prevent a page from being treated specifically. Inserting your logic on onGenerateRoute is scary. You understand a code does not mean that other developers will understand it.
> If you need to get the data somewhere and treat it, and you have another 300 different treatments, will you insert everything into onGenerateRoute? Sorry, but I can't see it as a possible alternative, I may be being opinionated about it, but this is just terrible from the perspective of project architecture.
> Using Middlewares is the most convenient and minimally maintainable way that a developer can go through to modify the browsing behavior.
> 
> If you need the page to have a redirect, you add that Middleware, otherwise, don't add it, you can reuse the Middleware on any page, and thus create defined rules for each one.
> 
> You can add the following redirect to a file that extends GetMiddleware:
> 
> GetPage redirect () => isLogged? null: RouteSettings (name: '/ login');
> 
> And ready.

How to continue the original operation after the forwarding operation returns?
