### ISSUE TITLE
Allow permanent with lazyPut

### ISSUE THREAD

**Issue by QuentinSc** [jonataslaw/getx#1117]
Hello!

**My use case**
I have a controller that load data from firebase during onInit.
This data can be used in several routes in my application. BUT may not be at all in some scenarios **. -> So I'm using lazyPut** 

However, when the data are loaded I want to keep it and not have to load them anymore, in other world I dont want the controller to be disposed if it has already been initialized.. **-> So I need the controller to be permanent**

**Describe the solution you'd like**
Make permanent controller with "lazyPut"

Thank you!

Quent

**Comment by jonataslaw** [comment]
Having a permanent controller can affect the 'fenix' mode, because if it is permanent, it will never be deleted, so there is no way 'fenix' mode is active.
Will get.delete do what with a permanent dependency that has fenix mode enabled?
I think this proposal needs a complete dependency injection roadmap, if you have one, we can think about implementing it.
However, being very opinionated, I believe that having a layered architecture with a repository, which treats requests with cache is the best option for your case, at least that is what I would do.

For me the controller should not have any responsibility for caching results, for me it is the full responsibility of the data layer.

**Comment by QuentinSc** [comment]
Hello @jonahzheng,

After some sleep, yes I'm agree, the data must be cached by the data layer. 
So I will cover my use case like that.

Thank you Johnny
