### ISSUE TITLE
generic type flutter problem

### ISSUE THREAD

**Issue by rupamking1** [jonataslaw/getx#1150]
class MyController <T> extends GetxController {
  static MyController <T> get go => Get.put(Hare2<T>());

}
error-
Static members can't reference type parameters of the class.
Try removing the reference to the type parameter, or making the member an instance member.dart(type_parameter_referenced_by_static)

**Comment by jonataslaw** [comment]
`static MyController get go => Get.put(Hare2());`

Everything is wrong, you are trying to insert a class that is not MyController as if it were MyController, you are using a getter to inject dependency. I am closing this issue because in addition to not being related to the package, it violates the main principles of OOP and dart conventions.
Please follow the documentation and make sure you saw a bug before opening an issue. Community channels are the ideal place for you to ask questions and learn from others. This space is only intended for bug reports.

**Comment by rupamking1** [comment]
please tell me can I achieve it any other way?
