### ISSUE TITLE
Getx delete all controller when Get.offNamed(Routes.HOME) but i dont want delete home controller.

### ISSUE THREAD

**Issue by adnankhan74444** [jonataslaw/getx#1461]
For Example:
I am using home controller into my home view home as multiple internal views but when i want to back from internal view i call Get.offNamed(Routes.HOME).Get.offNamed deletes all controller but i dont want to delete home controller ?

**Comment by adnankhan74444** [comment]
Get.offAll(() =>DashboardView(),binding: HomeBinding())

**Comment by adnankhan74444** [comment]
Another Example 
Home --> ScreenOne ---> ScreenTwo ---> ScreenThree press back button Get.offAll(() =>DashboardView(),binding: HomeBinding()) it delete homeController..

**Comment by roipeker** [comment]
Ideally GetX should use 1 controller for 1 view (where view = Route), 
if you need a controller that doesn't gets disposed, please use `Get.put(Controller(),persistent:true)` or use `GetxService` instead. You might also try `Get.lazyPut(() => Controller(), fenix:true);` anywhere in your code, that will work as a regenerator of Controllers when they gets disposed... but isn't a good practice, as u don't have much control over the lifetime of your controllers ...

**Comment by quocviet1996** [comment]
So I have the same case, my project according to nested navigation with bottom navigation with have 4 page A,D,F,G,with example page A->B->C->A what i need is when i run get.offallNamed in C page to back to my A page i want this Acontroller is recreate. Because i have some function in that C page that can change the data display in A page, so when i go back to A page, i want that page will run oninit or something to run my Api to update that data display. If you suggest me use pernament sorry i can't, because i want when change bomttom tab example from A to D and go back, i want AController still recreate to update all view

**Comment by jonataslaw** [comment]
Update GetX to lastest version
