### ISSUE TITLE
[Question] GetX force update

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#1482]
When using GetX, can we force update by calling refresh inside the GetxController?

**Comment by jonataslaw** [comment]
Do you mean using the `refresh() ` method that inherited from ListNotifier, or the `rxvar.refresh()` of a reactive model class?

**Comment by jasonlaw** [comment]
Thanks for the reply.

I mean the refresh() method that inherited from ListNotifier.

I have tried but it seems not update, however, with GetBuilder it does.

Thank you.

**Comment by KevinZhang19870314** [comment]
I think this is by design, `refresh()` method should only be worked when wrapped by `GetBuilder`.

Code in `ListNotifier`, you can see `refresh()` method call the `_notifyUpdate`, which will execute the `GetStateUpdate` callback.

And `GetStateUpdate` callback list will be added in `GetBuilder` class `initState` method, which actually is a wrapper of `setState`, so when you force call refresh, it will do `setState` for the `GetBuilder` stateful widget, that's it. 

I am not 100% sure about this, could you please correct me? @jonataslaw 

code in ListNotifier
```
List<GetStateUpdate?>? _updaters = <GetStateUpdate?>[];

  void _notifyUpdate() {
    for (var element in _updaters!) {
      element!();
    }
  }

  @override
  Disposer addListener(GetStateUpdate listener) {
    assert(_debugAssertNotDisposed());
    _updaters!.add(listener);
    return () => _updaters!.remove(listener);
  }
``` 
code in GetBuilder
```
  /// Register to listen Controller's events.
  /// It gets a reference to the remove() callback, to delete the
  /// setState "link" from the Controller.
  void _subscribeToController() {
    _remove?.call();
    _remove = (widget.id == null)
        ? controller?.addListener(
            _filter != null ? _filterUpdate : getUpdate,
          )
        : controller?.addListenerId(
            widget.id,
            _filter != null ? _filterUpdate : getUpdate,
          );
  }

  /// Experimental method to replace setState((){});
  /// Used with GetStateUpdate.
  void getUpdate() {
    if (mounted) setState(() {});
  }
```

**Comment by jonataslaw** [comment]
> I think this is by design, `refresh()` method should only be worked when wrapped by `GetBuilder`.
> 
> Code in `ListNotifier`, you can see `refresh()` method call the `_notifyUpdate`, which will execute the `GetStateUpdate` callback.
> 
> And `GetStateUpdate` callback list will be added in `GetBuilder` class `initState` method, which actually is a wrapper of `setState`, so when you force call refresh, it will do `setState` for the `GetBuilder` stateful widget, that's it.
> 
> I am not 100% sure about this, could you please correct me? @jonataslaw
> 
> code in ListNotifier
> 
> ```
> List<GetStateUpdate?>? _updaters = <GetStateUpdate?>[];
> 
>   void _notifyUpdate() {
>     for (var element in _updaters!) {
>       element!();
>     }
>   }
> 
>   @override
>   Disposer addListener(GetStateUpdate listener) {
>     assert(_debugAssertNotDisposed());
>     _updaters!.add(listener);
>     return () => _updaters!.remove(listener);
>   }
> ```
> 
> code in GetBuilder
> 
> ```
>   /// Register to listen Controller's events.
>   /// It gets a reference to the remove() callback, to delete the
>   /// setState "link" from the Controller.
>   void _subscribeToController() {
>     _remove?.call();
>     _remove = (widget.id == null)
>         ? controller?.addListener(
>             _filter != null ? _filterUpdate : getUpdate,
>           )
>         : controller?.addListenerId(
>             widget.id,
>             _filter != null ? _filterUpdate : getUpdate,
>           );
>   }
> 
>   /// Experimental method to replace setState((){});
>   /// Used with GetStateUpdate.
>   void getUpdate() {
>     if (mounted) setState(() {});
>   }
> ```

You're right, `refresh()` (predecessor to `update()`) will only work with `GetBuilder`.

@jasonlaw I think it is not a good solution to try to force the update of a reactive variable using `refresh()`, first because it doesn't work, and second because even though it has an GetBuilder ancestor that is updated and ends up updating the state, this is a bad solution that plays in garbage the biggest advantage of using GetX which is the construction optimization of the exact widget that was changed

**Comment by jasonlaw** [comment]
Thanks for all the clarifications, I am clear now, thank you very much!
