### ISSUE TITLE
Getx wrongly detect "the improper use of a GetX"

### ISSUE THREAD

**Issue by ChauCM** [jonataslaw/getx#1763]
I having this code:

```
// my view
Obx(() => MyCustomWidget(
                controller.listData,
              )),


// my CustomWidget 
class MyCustomWidget extends StatelessWidget {
  MyCustomWidget(this.listData)

  final dynamic listData;


  @override
  Widget build(BuildContext context) {

    return ListView(
      scrollDirection: Axis.horizontal,
      physics: ClampingScrollPhysics(),
      children: listData.map<Widget>((e) => MyDisplayWidget(e)),
    );
  }
}
```

I got the bug 
      [Get] the improper use of a GetX has been detected. 
      You should only use GetX or Obx for the specific widget that will be updated.
      If you are seeing this error, you probably did not insert any observable variables into GetX/Obx 
      or insert them outside the scope that GetX considers suitable for an update 
      (example: GetX => HeavyWidget => variableObservable).
      If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.

However, without MyCustomWidget, it works fine.

```
// my view
Obx(() => ListView(
      scrollDirection: Axis.horizontal,
      physics: ClampingScrollPhysics(),
      children: controller.listData.map((e) => MyDisplayWidget(e)),
    )),
    
```
    
 The MyCustomWidget is necessary because it help me save reuse this widget in different part of the app. I use the obs variable exactly the same way but one is allow and other is forbidden?
 
Ways I had try but still not working: use Getview insteald of StatelessWidget for MyCustomWidget; change dynamic listData to RxList listData;

**Comment by jonataslaw** [comment]
Initially, this is not a bug, it is an alert that forces you to code in the least expensive and most performant way possible. If in the future you insert 300 built-in widgets into your class, you will rebuild 300 widgets instead of just 1.
You're not componentizing anything, ListView.builder does exactly what this code does, and it's a ready-made Flutter component, with the advantage of only rebuilding the visible part.
But if you want to continue this, you can "bypass" GetX by using:

`controller.listData.toList()`

This is not a recommendation, but if you want to do it, go ahead.

**Comment by ChauCM** [comment]
Add .toList() works. Closing the ticket

Thank you for the support!

**Comment by ericomine** [comment]
@jonataslaw
I really like GetX syntax and all, but I do often have a hard time with RxLists in Obx. For instance, I'm currently working on an app which has a set of filters which pops up as a bottom sheet when the user clicks on a button:

```dart
// this is 
void showFilter(BuildContext context) async {
    // below is just an extension method which calls showModalBottomSheet
    await context.showCustomModalBottomSheet( 
      child: Obx(
        () => CustomSimulatorFilterSheet(
          // the 4 lists below are declared as final filters = <Filter>[].obs; in the controller 
          brands: controller.brandsFilters,
          establishments: controller.establishmentsFilters,
          selectedBrandIds: controller.selectedBrandIds,
          selectedEstablishmentIds:
              controller.selectedEstablishmentIds,
          onToggleEstablishment: controller.onToggleEstablishment,
          onToggleBrand: controller.onToggleBrand,
          onClearSelectedBrands: controller.onClearSelectedBrands,
          onClearSelectedEstablishments:
              controller.onClearSelectedEstablishments,
          onApply: controller.onFiltersChanged,
        ),
      ),
    );
  }
```

This throws an "improper use" exception, but I don't want to be forced to use Obx inside my bottom sheet component, because this way it might be reusable in some other project which does not use GetX. In this case, I do think that `Obx => Heavy bottom sheet => { FilterA, Filter B }` would make more sense that `Heavy bottom sheet => { Obx => FilterA, Obx => Filter B }`.

Maybe you could add the "toList()" workaround information to the message in the exception, it'd be very helpful when the developer does not want to push the Obx widgets further down in the widget tree.
