### ISSUE TITLE
Is there a way to find the controller according to the route

### ISSUE THREAD

**Issue by cyz1901** [jonataslaw/getx#2103]
I'm sorry, I'm a novice at Getx and flutter.
I have four pages.
A->B->C and D

D is a network error page.
When entering the page, if internet times out, it will navigate to D.

A->D
B->D
C->D

D can return to the previous page and call the network again to request data.

Because OnInit() only happens once in the life cycle of the controller, I definitely use the functions in the controller to pull the data again.

for example:
A->B->no network ->C ->automatic pilot -> D
So when the network is restored.
D ->back-> C(should reload data from network used CController.fetchAllData() called in D botton onTab() {})

But the key problem is that I can't explicitly declare the controller in D.

Because the controller may be C, B or A......
`final GetxController controller = Get.find();`
No effect

Could you give me some suggestions, or my idea of dealing with network failure navigation is wrong?
Thanks!

**Comment by cyz1901** [comment]
Maybe we could use middleware to realize some functions?

**Comment by rfmanuj** [comment]
Umm, thats a pretty interesting problem.

Let's make a little brainstorming here. Let's call this 4 pages a group of pages. You could have a "GroupPagesController extends GetxController", right?

Now, as you said, the controller may be C,B or A... that's a problem... Create an abstract class (lets call this SuperController). SuperController must extends GetxController, and must have an abstract method called reInit().

Now, you could have ControllerA extends SuperController, ControllerB extends SuperController... and so on.

Do you remember the GroupPagesController? This should hold an instance of SuperController, so that, when you redirect from C to D, for example, before the redirection (that's it, while you are in C), you would do `Get.find<GroupPagesController>().fallbackController=ControllerC`. When you are on D, and you will go back to C, before going to C, you will call `Get.find<GroupPagesController>().reInit()`.

Doing that, will allow you to initialize again your controllers, and, because PageD only works with SuperController, doesn't care about the specific implementation.
Obviouslly, you will have to register the GroupPagesController when your app init or handle the posibility that it's not registered when you wan't to use it (i.e. register if if it's not). 

I think this should solve your problem.

**Comment by cyz1901** [comment]
> Umm, thats a pretty interesting problem.
> 
> Let's make a little brainstorming here. Let's call this 4 pages a group of pages. You could have a "GroupPagesController extends GetxController", right?
> 
> Now, as you said, the controller may be C,B or A... that's a problem... Create an abstract class (lets call this SuperController). SuperController must extends GetxController, and must have an abstract method called reInit().
> 
> Now, you could have ControllerA extends SuperController, ControllerB extends SuperController... and so on.
> 
> Do you remember the GroupPagesController? This should hold an instance of SuperController, so that, when you redirect from C to D, for example, before the redirection (that's it, while you are in C), you would do `Get.find<GroupPagesController>().fallbackController=ControllerC`. When you are on D, and you will go back to C, before going to C, you will call `Get.find<GroupPagesController>().reInit()`.
> 
> Doing that, will allow you to initialize again your controllers, and, because PageD only works with SuperController, doesn't care about the specific implementation. Obviouslly, you will have to register the GroupPagesController when your app init or handle the posibility that it's not registered when you wan't to use it (i.e. register if if it's not).
> 
> I think this should solve your problem.


Thank you for your help !
hmmmm i try it.
```
Get.find<GroupPagesController>().fallbackController=ControllerC
```
This means that we need to define some mapping relationships in `GroupPagesController` to help us find the correct controller, right?

I used `GetxService` to store some objects in memory(lasting)  -----> `GroupPagesController extend GetxService`

Therefore, the following logic exists?(in GroupPagesController)
```
SuperController findController(String? routeName) {
   if(routeName == 'cccccc'){
      return Get.find<CController>;
  }else if(routeName == 'bbbb') {
     return Get.find<BController>;
  }
}
```

**Comment by rfmanuj** [comment]
Hi @cyz1901 

Sorry for the late replay.

The main point of having a "SuperController" is not to be worried about that nasty if.

I'm posting here some sample code, sorry if I couldn't make myself explain.

Define your super controller.

```dart
class SuperController extends GetxController {
  
  late SuperControllerDelegator? previousPageController;
  
  void reInit(){
    if(previousPageController != null){
      this.previousPageController!.reInit();
    }
  }
  
}
```

Define a controller delegator (note that here you can or can not extends the GetxController, it deppends on your needs):
```dart
abstract class SuperControllerDelegator extends GetxController{

  void reInit();
}

```

Make your specific controllers extends your delegator:
```dart
class ControllerA extends SuperControllerDelegator{
  @override
  void reInit() {
    // TODO: Here goes the code to initialize again your page A
  }

}

class ControllerB extends SuperControllerDelegator{
  @override
  void reInit() {
    // TODO: Here goes the code to initialize again your page B
 }

}
```


At startup time (i.e, when you app loads and initialize all your stuff), you have to register your super controller:
```dart
Get.put(SuperController());
```

So that, your controller is already registered.

Now, imagine you are on page A (for example, like this)
```dart
class PageA extends StatelessWidget{

  late ControllerA myController;

  void redirectToPageD(){
    Get.find<SuperController>().previousPageController = this.myController;
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    throw UnimplementedError();
  }

}
```

The PageD will look like:
```dart

class PageD extends StatelessWidget{


  void redirectToPreviousPage(){
    Get.find<SuperController>().previousPageController!.reInit();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    throw UnimplementedError();
  }

}
```

If you want the `reInit()` method to return a Future, you can show a loading widget before redirecting.

Doesn't this works on your problem?

**Comment by cyz1901** [comment]
> Hi @cyz1901
> 
> Sorry for the late replay.
> 
> The main point of having a "SuperController" is not to be worried about that nasty if.
> 
> I'm posting here some sample code, sorry if I couldn't make myself explain.
> 
> Define your super controller.
> 
> ```dart
> class SuperController extends GetxController {
>   
>   late SuperControllerDelegator? previousPageController;
>   
>   void reInit(){
>     if(previousPageController != null){
>       this.previousPageController!.reInit();
>     }
>   }
>   
> }
> ```
> 
> Define a controller delegator (note that here you can or can not extends the GetxController, it deppends on your needs):
> 
> ```dart
> abstract class SuperControllerDelegator extends GetxController{
> 
>   void reInit();
> }
> ```
> 
> Make your specific controllers extends your delegator:
> 
> ```dart
> class ControllerA extends SuperControllerDelegator{
>   @override
>   void reInit() {
>     // TODO: Here goes the code to initialize again your page A
>   }
> 
> }
> 
> class ControllerB extends SuperControllerDelegator{
>   @override
>   void reInit() {
>     // TODO: Here goes the code to initialize again your page B
>  }
> 
> }
> ```
> 
> At startup time (i.e, when you app loads and initialize all your stuff), you have to register your super controller:
> 
> ```dart
> Get.put(SuperController());
> ```
> 
> So that, your controller is already registered.
> 
> Now, imagine you are on page A (for example, like this)
> 
> ```dart
> class PageA extends StatelessWidget{
> 
>   late ControllerA myController;
> 
>   void redirectToPageD(){
>     Get.find<SuperController>().previousPageController = this.myController;
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     // TODO: implement build
>     throw UnimplementedError();
>   }
> 
> }
> ```
> 
> The PageD will look like:
> 
> ```dart
> class PageD extends StatelessWidget{
> 
> 
>   void redirectToPreviousPage(){
>     Get.find<SuperController>().previousPageController!.reInit();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     // TODO: implement build
>     throw UnimplementedError();
>   }
> 
> }
> ```
> 
> If you want the `reInit()` method to return a Future, you can show a loading widget before redirecting.
> 
> Doesn't this works on your problem?

Thank you. I think it's a more elegant realization
