### ISSUE TITLE
Simple code But not Change Icon?

### ISSUE THREAD

**Issue by ashokavarthanan** [jonataslaw/getx#2173]
return GetBuilder<IconController>(
        builder: (controller) => Scaffold(
              body: IconButton(
                icon: Icon(
                  controller.changeIcon ? Icons.done_all : Icons.error_outline,
                ),
                onPressed: () {
                  controller.changeIcon = !controller.changeIcon;
                },
              ),
            ));

the **Icon** Not changing ...

But Normal way Works.

	return Scaffold(
	  body: IconButton(
		icon: Icon(
		  changeIcon ? Icons.done_all : Icons.error_outline,
		),
		onPressed: () {
		  setState(() {
			changeIcon = !changeIcon;
		  });
		},
	  ),
	);

**Comment by fahmi277** [comment]
please add ' update ' for GetBuilder after your change

controller.changeIcon = !controller.changeIcon;
update()

hopely can solve your problem ::)

**Comment by RizaldiWiratama** [comment]
dont forget to use .obs in the end of value for variable `changeIcon`


```
class IconController extends GetxController {
  final changeIcon = false.obs;
}
```

use it in GetBuilder like this 

```
GetBuilder<IconController>(
    builder: (controller) => Scaffold(
          body: IconButton(
            icon: Icon(
              controller.changeIcon.value ? Icons.done_all : Icons.error_outline,
            ),
            onPressed: () {
              controller.changeIcon.value = !controller.changeIcon.value;
              controller.update();
            },
          ),
        ));
```

so u should add `.value` in `controller.changeIcon` because it is boolean variable (same with type int & String too ,but not for List)

and because you use GetBuilder, you should update the view with `controller.update();`

=============


later i recommend you to change the code : 
1. use only GetX / Obx (dont use GetBuilder) because we dont need to add `controller.update();` if using that GetX / Obx 
2. you should fix your logic code to be inside Controller, not in a View

**Comment by ashokavarthanan** [comment]
Thanks for Replay.
Problem Solved.
Thanks.

**Comment by RizaldiWiratama** [comment]
use GetX/Obx only in a Widget that the view will be changed later.. 

avoid use GetBuilder in start of Scaffold is just like you using StatefulWidget if you using that way...
