### ISSUE TITLE
[5.0.0-beta.30] RX type refresh become protected

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#2210]
Any reason why the RX refresh is becoming protected? 
I need to call the refresh method outside of the class, any alternative way for that?

**Comment by jasonlaw** [comment]
using trigger will do the trick.

**Comment by jonataslaw** [comment]
Sorry for the delay, I'm really busy, and rewriting the documentation for version 5 is going to be painful.
But yes, technically trigger will do the job. The refresh api has been unified, because now the Rx are notifiers based on the same class as the GetxControllers, so they won't be accessible from outside the class

**Comment by jasonlaw** [comment]
No worries. 
Getx is a great framework and I really appreciate your works here. 
Looking forward the stable version 5 release! :)

**Comment by fisforfaheem** [comment]
how to use a trigger???? i used to write .refresh and it did the world easily... how t do that In new version
