### ISSUE TITLE
new code maintainer

### ISSUE THREAD

**Issue by Macacoazul01** [jonataslaw/getx#2541]
Getx could have a new code maintainer (two more would be nice)

There are many opened pull requests and issues, and @jonataslaw don't have the time to keep upgrading the package on the speed the users need.

**Comment by cliftonlabrum** [comment]
Ah, the joys of open source software! 😅

**Comment by Zack-Heisnberg** [comment]
why there is no new maintainer ? ,because only jonataslaw knows his code , lot of code is undocumented and doesn't follow any patterns

**Comment by Macacoazul01** [comment]
It's more because there's no one with permissions to approve pull requests and publish on pub dev

**Comment by Macacoazul01** [comment]
.

**Comment by Macacoazul01** [comment]
I thought that he would return maintaining the code but as this hadn't happened... i've a proposal to the community:

We can create on this or other issue a tread where people interested in (and capable of) becoming a maintainer add their comments talking a little about their experience with getx and flutter, and the two more upvoted would be the ones, if @jonataslaw approve this.

**Comment by Zack-Heisnberg** [comment]
the whole project is based on a wrong concept , seriously want to be a good flutter dev ? learn context , and use something professional lel

**Comment by Macacoazul01** [comment]
People use the package and even after a year without a serious maintaining circle it's still be most liked one in pub dev.

It is built around a "wrong" concept, but is the easiest way of building a flutter app. 

Not everyone has the team,  resources and time to build it the right way from the start and for the most use cases it fit as not every app need to control the context so strictly.

**Comment by Macacoazul01** [comment]
The final user don't care which package you have to handle navigation, context, picking files...

They care about what you deliver to them.

Time to leave the keyboard and start talking with the design and final users too if you wanna be this "good flutter dev".

**Comment by Zack-Heisnberg** [comment]
this seem some junior developer talk , depending on your final user and your level of ethics you can use what ever you want ,

but i think every client deserves to get a maintainable and understandable code

when i start time ago on flutter i did use this package  , it's was on my personal projects and i did find some problems that i couldn't fix , infact i faced some issues that are open issues since more then 7 months , explain that to your client or try to fix it your self seeing how undocumented and like Spaghetti source - code , you can see the issues in this github

then i started working with a team and see lot of reasons why i shouldn't use this , our project used flutter_bloc , 
took me more then 20 days to fully get it , it's flutter favorite for a reason and i got 0 issues , i am not recommending it or anything i am just saying learning and using getx was waste of time for me

**Comment by Macacoazul01** [comment]
If getx is this sort of problem to you, why are you here wasting your time in this thread on the first place?
You don't seem like wanting to help fix the code

**Comment by Zack-Heisnberg** [comment]
> If getx is this sort of problem to you, why are you here wasting your time in this thread on the first place? You don't seem like wanting to help fix the code

i am not , i commented [on Oct 22, 2022] and haven't been here

just when you commented on this old issue i got an email notification so i checked

**Comment by jonataslaw** [comment]
I'll review the PRs, and add more code maintainers.
I'm pretty busy, so the PRs being leaked is my fault, but that will be fixed this week when I'm off work, and I'll use my time to push the release candidate to stable, accept the PRs, and add people who want to contribute to the project.
