### ISSUE TITLE
will be v5.0?

### ISSUE THREAD

**Issue by curonny** [jonataslaw/getx#2625]
will be v5.0?

**Comment by adepauldami** [comment]
lovely

**Comment by kauemurakami** [comment]
@jonataslaw  An idea that I would like to leave, based on experiences with the backend I am trying to centralize the throwing of errors with zonerunGuarded, this option in our GetMaterialApp would be a good one.

And aaa, GetMaterialApp.router is turning out really cool, I even found a way around the problem with hot reload on the web. Congratulations.

**Comment by LeeCareFree** [comment]
wait in hope

**Comment by heralight** [comment]
Hi!
@jonataslaw, thank you very much for this framework!

I am testing it, and I realize that the code on Github is inconsistent in the master and 4.6.5 branches.

From what I understand, master corresponds to version 5 beta, so the examples are updated with this version.
On the other hand, the 4.6.5 branch has nav2 example code that uses the master api. You have to go back to the 4.6.1 tag to have the right code.
For example, in [4.6.5 branch inside ./example_nav2/lib/app/middleware/auth_middleware.dart](https://github.com/jonataslaw/getx/blob/4.6.5/example_nav2/lib/app/middleware/auth_middleware.dart)

this code use RouteDecoder.fromRoute instead of GetNavConfig.fromRoute

https://github.com/jonataslaw/getx/blob/4.6.1/example_nav2/lib/app/middleware/auth_middleware.dart


best regards,

Alexandre

**Comment by curonny** [comment]
i see complicated v5.0

**Comment by thailocnexle** [comment]
love it! thank

**Comment by duc1205** [comment]
@jonataslaw when release 5.0.0
