### ISSUE TITLE
NEW UPDATE  of FLUTTER! 

### ISSUE THREAD

**Issue by curonny** [jonataslaw/getx#2667]
Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.

**Comment by kauemurakami** [comment]
I just got this same error on my github actions with the latest version of flutter.

`/opt/hostedtoolcache/flutter/stable-3.7.0-x64/.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/material_with_modal_page_route.dart:4:1: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
import '../modal_bottom_sheet.dart';
^^^^^^^^^^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/stable-3.7.0-x64/.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:28:13: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/stable-3.7.0-x64/.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:50:10: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;`
  
  Initially I didn't see any relationship for pointing to flutter's package, but since almost all my bottomsheets are opened with get I came to check if anyone else was having this, are you running your app in debug mode?
send a sample of your error if you can, if it points to the implementation location in the code.
I will try to resolve this.
@curonny

**Comment by jonataslaw** [comment]
I will investigate this today

**Comment by 253nomi** [comment]
I have upgraded my flutter version from 3.3.10 to 3.7.0 and now getting the following error.

ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart

I tried to follow this [Error: 'ModalBottomSheetRoute' is imported from both](https://stackoverflow.com/questions/74751803/error-modalbottomsheetroute-is-imported-from-both) but solutions didn't work for me.

**Comment by umairshah143** [comment]
any solution please?

**Comment by jonataslaw** [comment]
I tested the new version, and it seems to work fine.

The error codes are related to other libs (mainly package:modal_bottom_sheet). However, if there are any issues with GetX, please don't hesitate to let me know.

**Comment by DholaSain** [comment]
> I tested the new version, and it seems to work fine.
> 
> The error codes are related to other libs (mainly package:modal_bottom_sheet). However, if there are any issues with GetX, please don't hesitate to let me know.

I've updated the package (locally) for my personal project. The owner of this lib is not responding. should I publish it myself or wait for the owner to fix it?

**Comment by curonny** [comment]
> > I tested the new version, and it seems to work fine.
> > The error codes are related to other libs (mainly package:modal_bottom_sheet). However, if there are any issues with GetX, please don't hesitate to let me know.
> 
> I've updated the package (locally) for my personal project. The owner of this lib is not responding. should I publish it It 

would be great, I don't know if the owner is aware of the package. I'm worried they left that free, I don't think there is v5 or wait for the owner to fix it?

**Comment by ndeepak** [comment]
Getting the same error.. still trying to figure out what to do.. if any body have any solution, it would be very helpful
![image](https://user-images.githubusercontent.com/79294472/215279517-730ee32b-ebf7-47f8-9aad-a3c64db211ae.png)

**Comment by jokilic** [comment]
@ndeepak
I think you should specify the latest ModalBottomSheet version from GitHub in your pubspec.yaml.

Check the latest commit: https://github.com/jamesblasco/modal_bottom_sheet/commits/main

**Comment by kauemurakami** [comment]
@ndeepak 
To fix the error, without upgrading flutter, running locally I can use it with Flutter 3.3.10 - Dart 2.18.6 DevTools 2.15.0.

**Comment by jonataslaw** [comment]
Since none of the reported bugs have anything to do with Getx, I'm closing this issue.

Feel free to open another issue if you find any errors related to GetX

**Comment by mahmood1328** [comment]
modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
