### ISSUE TITLE
Suggestion for migration?

### ISSUE THREAD

**Issue by asterd** [jonataslaw/getx#2691]
I'm very sorry to say that. I love GetX and use it for two production apps with high satisfaction. But since @jonataslaw doesn't interact anymore with its community, I think that this project is dead and If I want to develop a new app or bring the already developed app for other years, I need to migrate to something else.
Someone can suggest some other package that can help migration?

**Comment by gladson** [comment]
My dear so I found this way to get in touch with him.

borgesadvocacia@adv.oabsp.org.br
jonataborges01@gmail.com
jonatas@iris.finance

**Comment by asterd** [comment]
Thanks @gladson.
I'll try to contact him... I think that all the community wants only to know if this project continue or not... I hope yes, but I think not...

**Comment by Ben8557** [comment]
I am learning Bloc to switch as GetX is no more maintained.

**Comment by kauemurakami** [comment]
I have a project that I've been studying for some time but never made available.

It has almost the same syntax as getx in the initial versions, but based on what is already in flutter.
Application lifecycle control, providers with inheritedwidget, observables based on value notifier, I've been dating the idea for a long time, but because I can't get rid of the context in some situations, and there's no need while get is still alive, and I always use it in my projects, I never saw any reason.

But now I'm applying it in a real project, at this moment, I'm testing it with nav2.0, and in several other contexts, thinking about the worst case scenario, of get not being maintained, I can create a release for you to try.

**Comment by asterd** [comment]
@kauemurakami this can be a very powerful scenario!

**Comment by kauemurakami** [comment]
> @kauemurakami this can be a very powerful scenario! 

I'm still hoping that the package will be maintained, even so this week I revived the project, and I'm trying/creating the example. by the end of this week I should finish an alpha, because this time I decided to use it in a personal project, anyway now I'm going to finish this implementation. 
I update you here on this issue.

**Comment by kauemurakami** [comment]
@asterd

**Comment by kauemurakami** [comment]
> @kauemurakami this can be a very powerful scenario! 

@asterd 
I'm still hoping that the package will be maintained, even so this week I revived the project, and I'm trying/creating the example. by the end of this week I should finish an alpha, because this time I decided to use it in a personal project, anyway now I'm going to finish this implementation.
I update you here on this issue.

**Comment by asterd** [comment]
@kauemurakami perfect!
thanks a lot.. 
I hope too that the project will continue to live but, at this point, I'm afraid not. However, a project like yours, if it works well, could really give a valid alternative to a huge amount of developers who today have relied on getx and who risk getting stuck.

**Comment by kauemurakami** [comment]
@asterd 
> @kauemurakami perfect!
> thanks a lot.. 
> I hope too that the project will continue to live but, at this point, I'm afraid not. However, a project like yours, if it works well, could really give a valid alternative to a huge amount of developers who today have relied on getx and who risk getting stuck.

**Comment by kauemurakami** [comment]
> @kauemurakami perfect!
> thanks a lot.. 
> I hope too that the project will continue to live but, at this point, I'm afraid not. However, a project like yours, if it works well, could really give a valid alternative to a huge amount of developers who today have relied on getx and who risk getting stuck.

@asterd 
Yes, it does not match the principles and I have no idea of performance, as I said it is something personal that I have tried several times over time.
But as soon as this fear in the community, and even in myself, I decided to try again, it would be an alpha version, but it is the minimum necessary to manage the states.

I have a pinned version, missing an example, until the end of the week, it will be open.

**Comment by jonataslaw** [comment]
Who says GetX is no longer supported?
The update to version 5 will be released this weekend.

**Comment by kauemurakami** [comment]
@jonataslaw hi gone, lets go! anything we are here

**Comment by jonataslaw** [comment]
I know I've been away from the community, but despite being swamped with work, I was trying to maintain my mental health (some comments really suck). But I worked weekends on the new version, and it's almost done.

**Comment by kauemurakami** [comment]
Yes, some people are extremely dependent, and do not understand that we are human, I imagined that from the beginning, everyone has their reasons, you yourself told me that this was your life's project, so I doubted very much that it would not continue, taking a while or not.

We are also facing extreme cases, dio has already gone 16 months without updates, it is still alive today, we see the owner of the dio yesterday, not being able to maintain the package for the same reason.

You did the community a favor and we should thank you, I wasn't worried about getx, but I saw people worrying and I actually worried about you, I don't know if you received my emails.

And don't worry, we're here. <3

**Comment by gladson** [comment]
> I know I've been away from the community, but despite being swamped with work, I was trying to maintain my mental health (some comments really suck). But I worked weekends on the new version, and it's almost done.

Well done, may you be back in full swing...
All of the getx community who really want the tool to succeed are on your side to support you.
Delete from your life those who don't do well and it's simple, just a delete button.
You've added to the community more than most people.
And the concern is due to the fact that there are several projects in several companies that use the package.

**Comment by LeeCareFree** [comment]
> Who says GetX is no longer supported? The update to version 5 will be released this weekend.

look forward to！！！

**Comment by asterd** [comment]
@jonataslaw thanks for your answer.
I know that mantain a project like this can be very difficoult and, as any other human, you must first mantain your mentale health.. but you know: Getx has a very big community of end users but only you as a main mantainers.. and since It Is the backbone of a very big Number of apps and flutter run with many releases, I think Is also human ti ha e fear that the project Will be dead After 2/3 months without a commit.. so, Sorry for the hipe, I'm very very Happy that the project Will go ahead and I Hope that also the rest of flutter community Will change it's mind on this package...

**Comment by chejdj** [comment]
@asterd suggest close this issue.
