### ISSUE TITLE
Exception: GetRoot is not part of the three in ^5.0.0-release-candidate-3

### ISSUE THREAD

**Issue by gkdgo** [jonataslaw/getx#2731]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When I change themeMode by Get.changeThemeMode(ThemeMode.light); the error shows

**Reproduction code
```dart 
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(const MyApp());
}
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp>{
  @override
  void initState() {
    super.initState();
    Get.changeThemeMode(ThemeMode.light);
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      home:  Container(height: 100,child: Text('data'),),
      // translations: TranslationService(),
      // locale: window.locale,
      // fallbackLocale: const Locale('zh', 'CN'),
    );
  }
}
```
**To Reproduce**
run main.dart on macos

**Screenshots**
<img width="784" alt="image" src="https://user-images.githubusercontent.com/55651847/223628892-9967c3c2-7f87-4f7e-b9ee-9570c10a4788.png">

**Flutter Version:**
3.7.3

**Getx Version:**
^5.0.0-release-candidate-3

**Comment by gkdgo** [comment]
> 

thank you , you are right , but it works fine in ^4.6.5, and here is still a new problem in `Get.changeThemeMode` please refer to [#2734](https://github.com/jonataslaw/getx/issues/2734)

**Comment by jonataslaw** [comment]
Yeah, you have reason, the versions 4* it have worked due to a bug in the library that initialized every resource along with Flutter.
This made it possible to use global functions before initialization, but made it necessary to clean up dependencies after each test, as it had a global scope.

In the new version this does not happen, GetX resources are only allocated when it is initialized in GetRoot, and it is completely removed when GetRoot leaves the tree, facilitating testing and preventing bugs.
Now you must set the theme declaratively in GetMaterialApp, and setting it before startup will not work.
The issue related https://github.com/jonataslaw/getx/issues/2734 was fixed in the latest RC.
