### ISSUE TITLE
Need more frequent updates

### ISSUE THREAD

**Issue by gkdgo** [jonataslaw/getx#2807]
Hi @jasonlaw  thanks for your work on Get . 

I think you can release a update more frequently in `Prerelease` or `Rerelease` to prevent issues that have been fixed in this repo (but not updated in the Dart pub) from being raised again, and it can let people know the pkg is still updating(I found someone questioning whether Get is keeping updates).

And I need a `routerConfig` prop in `GetMaterialApp.router` , but I can't find in `5.0.0-release-candidate-4`(two month ago already), could you please release a update to include https://github.com/jonataslaw/getx/pull/2643

**Comment by yelkamel** [comment]
I just saw that GetX pub dev was not updated since almost a year !
I start to be affraid about using this great package because of that... Imagine if one day we got a new update of Flutter or Dart and this package didn't working anymore... 

I start to check other package solution, for the navigation I found some awesome but for state management GetX is so cool ! 
But please update the pub dev 😁🙏🏻

If you need help, I'm here !

**Comment by CarlosBernalA** [comment]
With the last update of flutter I detected a problem with the GetX library concerning routing, the controllers do not die when closing the dependent widget, the controller gets stuck which affects all the functionality of the application, my question is if it already Is this bug being worked on or what can be done about it?

**Comment by crazidev** [comment]
I think we should just figure out the problem and create a pull request

**Comment by CurrentIndex** [comment]
......(?)

**Comment by jefrisingh** [comment]
https://github.com/jonataslaw/getx/issues/2797#issuecomment-1555081896

**Comment by herowws** [comment]
I plan to give up on getx
