### ISSUE TITLE
obs confusion with docs and #223

### ISSUE THREAD

**Issue by ghenry** [jonataslaw/getx#285]
Carrying on from #223 and the example in the readme:

```
onInit(){
  ever(isLogged, fireRoute);
  isLogged.value = await Preferences.hasToken();
}

fireRoute(logged) {
  if (logged) {
   Get.off(Home());
  } else {
   Get.off(Login());
  }
}
```

I'm loading isLoggedin from shared prefs like above example. If I use `await` there, I get "await can only be using in an async functions", if I make it async, I get stuck and LoginScreen after boot up and logged in..

So I've created:

```
  @override
  void onInit() {
   _loadLoggedIn();
    ever(isLoggedIn, checkLoggedIn);
  }

  // Move to PrefRepository
  _loadLoggedIn() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    // expr1 ?? expr2
    //    If expr1 is non-null, returns its value; otherwise, evaluates and
    //    returns the value of expr2.
    // https://dart.dev/guides/language/language-tour#conditional-expressions
    isLoggedIn.value = prefs.getBool('isLoggedIn') ?? false;
    print('Loading isLoggedIn as "' + isLoggedIn.value.toString() + '" from device.');
  }
```

In checkLoggedIn:

```
void checkLogged(_) {
    if (isLoggedIn.value) {
      Get.off(HomeScreen());
    } else {
      Get.off(LoginScreen());
    }
  }
```

when my app starts from fresh again after a successful login, I see the LoginScreen() flash, then I go to the HomeScreen. My setup is as per #223

What am I doing wrong here?

**Comment by ghenry** [comment]
This is what I'm logging:

```
I/flutter (21847): [GET] GetMaterialController has been initialized
I/flutter (21847): [GET] AuthController has been initialized
I/flutter (21847): [GOING TO ROUTE] /
I/flutter (21847): [REPLACE ROUTE] /
I/flutter (21847): [NEW ROUTE] /loginscreen
I/flutter (21847): Loading isLoggedIn as "true" from device.
I/flutter (21847): [REPLACE ROUTE] /loginscreen
I/flutter (21847): [NEW ROUTE] /homescreen
```

**Comment by jonataslaw** [comment]
`ever` must is above the modification method.
You are listening for changes after the change, so ever() will never be triggered.
Also consider using https://pub.dev/packages/get_storage
It is synchronous (does not need await), and will make your life much easier if you don't have a lot of time on Flutter, and you still can't understand the flow of async/await/then from the Futures.

wrong
```
   _loadLoggedIn();
    ever(isLoggedIn, checkLoggedIn);
```
right
```
   ever(isLoggedIn, checkLoggedIn);
   _loadLoggedIn();
   
```

In version 3 I will remove SharedPreferences from the example, because it makes no sense to use it instead of get_storage.
It is slower, depends on platform channels, does not support flutter_desktop, and needs to be used with await as it has no cache.
get_storage solves all of these problems.

**Comment by ghenry** [comment]
Hi @jonataslaw 

Thanks for the pointers and get_storage recommendation. It still flashes the LoginScreen() though after this change, so I switched to get_storage and it's working. What did I miss here? Lack of understanding regarding Futures?

Thanks.
