### ISSUE TITLE
Named routing stack

### ISSUE THREAD

**Issue by zl910627** [jonataslaw/getx#291]
```Dart
GetMaterialApp(
    initialRoute: '/',
    getPages: [
        GetPage(
            name: '/',
            page: () => HomePage(),
        ),
        GetPage(
            name: 'first',
            page: () => First(),
        ),
        GetPage(
            name: 'second/:id',
            page: () => Second(),
        ),
        GetPage(
            name: 'third',
            page: () => Third(),
        ),
        //...
    ],
)
```

I have organized my routes like this.
```Dart
Get.toNamed('first');
...
Get.toNamed('second/123');
...
Get.toNamed('third');
```
Now navigate stack would be `/ > first > second > third`.

I have called below function at third page.
```Dart
Get.offAllNamed('/second/123')
```
What expected is `/ > second`, but navigation stack has only `second`.
i.e, missing of `/`

PS: Please ref below article.
https://medium.com/flutter-community/flutter-navigation-cheatsheet-a-guide-to-named-routing-dc642702b98c

Thank you.

**Comment by jonataslaw** [comment]
Hi zl910627, I don't know what this tutorial has to do with this package, but you are definitely using the wrong package.
Every stack starts with slash, and if you choose to use two different routes for the same name, one with arguments and one without, you should still keep one last slash at the end, to inform you that there is another route that will receive parameters.

I recommend that you never do this:
`Get.toNamed('first');`

I don't know if you have already tested the Flutter web, but you will get a hash and the name of your route in the front, and this can get you into trouble. So always start with slash, remembering that to use the same route for two different screens you must still use a slash at the end


```dart
 GetPage(
            name: '/second/',
            page: () => Second(),
        ),
 GetPage(
            name: '/second/:id',
            page: () => OtherPage(),
        ),
```
And don't use navigation without the bar too.

`Get.toNamed('/first');`

**Comment by zl910627** [comment]
Note: When you map a route to ‘/’ and you use a path like ‘/login’ the Navigator will push the HomeView and then the LoginView because of the deep linking functionality. Keep that in mind when doing routing.

**Comment by jonataslaw** [comment]
No, the Navigator does not do this, because it does "==" comparison
'/' is different from '/login', so the navigator only sends '/' if you explicitly send '/'

**Comment by zl910627** [comment]
You can try with some sample.
Navigator works exactly like that

> Note: When you map a route to ‘/’ and you use a path like ‘/login’ the Navigator will push the HomeView and then the LoginView because of the deep linking functionality. Keep that in mind when doing routing.

**Comment by zl910627** [comment]
What I exactly want is `/login` and 'login' should be different.
i.e, `/` also has his page and it should be pushed before `login` when `/login`
> No, the Navigator does not do this, because it does "==" comparison
> '/' is different from '/login', so the navigator only sends '/' if you explicitly send '/'

**Comment by jonataslaw** [comment]
This is not possible, I will only implement the subroutine system in navigator 2.0.
For now you can create your own logic for this (using split), or you can do some hack to stack the routes the way you want, example:

```dart
 getPages: [
      GetPage(name: '/second', page: () => First()),
      GetPage(
          name: '/second/foo',
          page: () {
            Future.delayed(Duration.zero)
                .then((value) => Get.to(Second(), duration: Duration.zero));
            return First();
          },
```
I am not recommending this, because it is a hack, but the behavior you want is not possible, or it would take a lot of unnecessary work, since every system will be redone with navigator 2.0, so you basically have 3 solutions:
1- Wait.
2- Use hack
3- Work on a solution for this and open a PR, because I definitely have no plan to support this until the arrival of the new Navigator.

Currently, each route is a route, regardless of how you stack it, that's Flutter's behavior.
Currently the library works as planned. But I understand the resource you want, however I cannot compromise the time I have available to update this library by inserting resources that will be eliminated in a few months. If one of the maintainers requests this feature, I will do it in my working time, otherwise you will only have him in a few months.

If you want to contribute to this, you can also open a PR.

**Comment by jonataslaw** [comment]
Note

> What I exactly want is `/login` and 'login' should be different.
NOTE-  This here hurts how things work on the web, it will never work that way.
'/' can be one route, and '/login' another, and you can call one before the other, but you can never use 'login' as a path, that's wrong.

**Comment by zl910627** [comment]
Hello @jonataslaw 
Thank you for your great support!
This issue could be really closed!
