### ISSUE TITLE
You have learned GetX, but you have not learned Flutter

### ISSUE THREAD

**Issue by herowws** [jonataslaw/getx#2954]
GetMaterialApp hides the most important BuildContext in Flutter from the root。
If you really want to learn Flutter, please abandon GetX。
GetX and Flutter have conflicting philosophies。
See the shadow of Android's xUtils in GetX。

**Comment by ByeongheeKim** [comment]
riverpod too.

**Comment by yang-lile** [comment]
With riverpod, you get references and context at the same time. It is great design for a flutter developer. 

Many functions of Getx are not perfect. Who will do international adaptation in a map??? Getx initially promised three major directions: state management, routing management, and internationalization. Now only Obx, which is state management, is awesome. Since context is not used, it is easy for beginners to operate routes in various any other places and cause errors. For internationalization, we have official solutions like flutter_localizations.

**Comment by Simple0Sample** [comment]
You don’t have to like it, and you don’t have to accept it. No one forces you to use it, but your message also conflicts with the concept of tolerating the creations of others. Are you not going to appear here?

**Comment by Pluto1219** [comment]
Work is all about being simple and fast, do you have any questions?

**Comment by jonataslaw** [comment]
This discussion seems to be inflamed by some level of fanboizism, and this is not good for the community, it is not good for personal or professional development, and it does not add anything to the Flutter community in general. That's why I'm closing it.
