### ISSUE TITLE
About the WebSocket issue

### ISSUE THREAD

**Issue by XiaoSGentle** [jonataslaw/getx#3031]
It's a pleasure to use Getx, it's excellent. I want to ask a question about GetConnect WebSocket, there seems to be some problem with the Sec-Websocket-Key in the request header, I don't know the reason, I use other languages to link to the specific server I created without error, I provide a screenshot here.
![image](https://github.com/jonataslaw/getx/assets/107936135/df3c1eda-a129-442e-ba18-a5da437bbb8c)

![image](https://github.com/jonataslaw/getx/assets/107936135/ac646b50-28d0-4d73-ad65-69ad65eae96d)

**Comment by PeterMX** [comment]
looks like the one in GetConnect is a 8 bytes while Gin requires a 16 byte one:
`var key = base64.encode(List<int>.generate(8, (_) => r.nextInt(255)));`
you should change that 8 for a 16 locally and use that, since looks like this project is dead,
the file is on `./lib/get_connect/sockets/src/sockets_io.dart` in line 105 in GetX 4.6.6
Good luck!

**Comment by XiaoSGentle** [comment]
> looks like the one in GetConnect is a 8 bytes while Gin requires a 16 byte one:看起来 GetConnect 中的那个是 8 字节，而 Gin 需要 16 字节： `var key = base64.encode(List<int>.generate(8, (_) => r.nextInt(255)));` you should change that 8 for a 16 locally and use that, since looks like this project is dead,您应该在本地将 8 更改为 16 并使用它，因为看起来这个项目已经死了， the file is on `./lib/get_connect/sockets/src/sockets_io.dart` in line 105 in GetX 4.6.6该文件位于 `./lib/get_connect/sockets/src/sockets_io.dart` GetX 4.6.6 中的第 105 行 Good luck! 祝你好运！

It worked , Thanks!
