### ISSUE TITLE
Get or GetX? 

### ISSUE THREAD

**Issue by maginkgo** [jonataslaw/getx#304]
I have some confusion about the package name, it would be nice to replace "Get" by "GetX" in the documentation. Or are they two different things ??

**Comment by jonataslaw** [comment]
> I have some confusion about the package name, it would be nice to replace "Get" by "GetX" in the documentation. Or are they two different things ??

Hi, until yesterday the name of the package was GET.
After numerous users complained that it was impossible to find lib content on Google due to SEO, it was renamed to GetX.
Despite changing the name to GetX, the functions continued to refer to Get for compatibility reasons. And although it is difficult to locate, users continue to call GetX Get.
You can call either one, just to search the internet the name GetX will be preferable starting today.
