### ISSUE TITLE
Get.toNamed preventDuplicates: false has no effect

### ISSUE THREAD

**Issue by giantss** [jonataslaw/getx#3048]
The version I am using is `get: 4.6.5`.

I read the description of the preventDuplicates parameter:

```
 /// By default, GetX will prevent you from push a route that you already in,
  /// if you want to push anyway, set [preventDuplicates] to false
```

page A -> page B -> page C -> page D -> page B

When I set preventDuplicates: false, page B was not refreshed when toNamed page B for the second time.
Can you help me find out what's going on? According to the documentation, page B should be refreshed.
@jasonlaw

**Comment by jonataslaw** [comment]
Do you want to open the page again, but with a new controller?
Because the new page was probably opened, but it must be using the previous page's controller.

**Comment by giantss** [comment]
@jonataslaw  

Thank you very much for taking the time out of your busy schedule to reply to me. The new interface (page B) and controller are unchanged from the previous page B.
I want to refresh the data in the page B interface when jumping to the same interface (the existing page B) again. I don't know how to do it.

**Comment by jonataslaw** [comment]
To better help you, it would be better to understand your business logic:
1- Will the previous page B be deleted from the stack? If so, you need some method like Get.off to remove it when going to the next route.
2- Will you maintain two versions of Page B? If so, it's better to use a GetWidget, or even a StatefulWidget, and keep the controller "Not global" since you can only have 1 global controller of the same type (in fact you can have more using tags , but this makes the code so complex, that I prefer not to use it, although I make it available to anyone who wants to use it).

**Comment by giantss** [comment]
Thank you again for your reply. I value your reply very much.

Yes, I will maintain multiple page B.
I replaced `GetView` with `GetWidget` and Hot Restart, but it still seems to be the same as before, with no effect.

<img width="616" alt="image" src="https://github.com/jonataslaw/getx/assets/13778798/d9cc28aa-c0da-480c-a956-721f8d14ab7b">

**Comment by jonataslaw** [comment]
Using GetWidget you need to use Get.create and not Get.put or Get.lazyPut.

**Comment by giantss** [comment]
My problem has been solved.
Thanks for the finishing touch.
It turns out that `GetWidget` needs to be used in conjunction with `Get.create` to achieve the effect I want.

**Comment by giantss** [comment]
I would like to ask if there is any other way to achieve my needs besides using `GetWidge`? I have a very complex interface and I don't feel like using GetWidge is appropriate.

@jonataslaw
