### ISSUE TITLE
ratio method is not being used anywhere

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/getx#322]
**Describe the bug**
On file `getx/lib/src/context_extensions/extensions.dart` line 21 `double ratio(){}`
It seems like this method is not available for the user, and i've noticed that you are not using it anywhere else.
I think it is a typo.

**To Reproduce**
1. Go to file `getx/lib/src/context_extensions/extensions.dart` line 21
2. Check if method `ratio` is being used or is available for use

**Expected behavior**
To be available via Get

**Screenshots**
![image](https://user-images.githubusercontent.com/11494727/86183319-20a46a80-bb08-11ea-87a0-291e84d590ed.png)

**Flutter Version:**
channel master, updated yesterday

**Get Version:**
3.1.2

**Comment by jonataslaw** [comment]
When using "context.ratio(dividedBy: 2)" do you get any errors?
These are the context extensions, which will be used as a shortener for some functions that use context.
The reason I created them instead of using Get.width for everything, is that the height and width of Get are the height and width of the screen, and that screen can change, for example, on the web, when the person resizes the window. To change in real time, context is necessary, and since I couldn't prevent the use of context in this situation, I just created an alias for it, to make it more comfortable to type.

**Comment by Nipodemos** [comment]
sorry, i've misunderstand your code, it is working normally.
Since i am here, what is the difference between `width` and `widthTransformer` ?

**Comment by jonataslaw** [comment]
One gives you the width of the screen, the other gives you the power to define half the screen now, a third of it and so on. Useful for responsive applications. This was a tool created by @Rilderralmeida and he emailed me instead of offering a PR. But I find it useful to keep the design responsive.

**Comment by Nipodemos** [comment]
Thank you for this description, i've put this on docs in #323
