### ISSUE TITLE
UserController not found. You need call put<UserController>(UserController()) before

### ISSUE THREAD

**Issue by marcobraghim** [jonataslaw/getx#327]
**Describe the bug**
This error is thrown when I try to find the instance with: `UserController userController = Get.find();` in other page.

I'm not sure, but seems that it shouldn't be happening. My doubt is about where I'm placing the lazyPut. Is that rigth? It's a possible bug?

Ps.: Get.put(UserController()) works well.

**To Reproduce**
```dart
void main() {
  Get.lazyPut<UserController>(() => UserController());

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.deepPurple,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      initialRoute: LoginPage.tag,
      getPages: [
        GetPage(name: LoginPage.tag, page: () => LoginPage()),
        GetPage(name: ChatPage.tag, page: () => ChatPage()),
      ],
    );
  }
}
```

**Flutter Version:**
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (2 weeks ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Get Version:**
get: ^3.1.4

**Describe on which device you found the bug:**
Android Nexus5 (emulator) R - Kernel 4.14 - On Linux

**Comment by jonataslaw** [comment]
You can monitor the log to be sure, but I believe that your lazyPut is being removed from memory, because the first page that called it has been removed from memory.
Despite looking like a "singleton" or a kind of "service locator", the instance manager is highly linked to the page that called it first, and if you remove it from the stack, it will be removed from memory. Get.find() is not an instance maker, but just a "shortcut" to somewhere, and that place is saved in a map in memory, so when you call it, you're not creating an instance, you're basically doing a "Type get to => RealInstance".
The problem is when you use an instance for the first time, Get does something like this:
Type instance registered in memory, in path X, and the currentRoute of that instance is Y.
The rules are as follows:
1- While that instance is in the foreground, all services that need it will point to the same memory space, and will get the same instance.
2- If any "daughter" route needs it, and it still remains on the stack, Get will deliver the same instance.
3- If the first route that used that instance is arranged, the instance and all the services connected to it will be arranged (yes, if you put an API Service, and call it your controller, it will also be arranged, and not me ask how this is done, that I will have to write a book here).
4- And the problem: When you register a lazyPut, you are not registering an instance. You can look at the dart inspect, and you won't see any instance of that object in memory. You are just registering a function, which if called, will generate an instance. This function is temporarily stored in memory. It occupies less than 16bytes (which is very little, 100 of them would give 1.6kb, 100 thousand of them would give 1.6mb). But assuming that nothing that was created, and would not be used, remains in memory, when creating the instance, in full mode, the function is deleted from memory. I know, this is totally irrelevant, and I might as well keep these factories in memory, but I don't want to see someone benchmark by inserting 10 million controllers into memory, removing and saying that the application got 16mb more garbage. It's too hasty, but the default option does that. So it's much easier to just use SmartManagement.keepFactory, and when you need that instance again, it will be manufactured and delivered to you again.

/////// Portuguese version (não confio tanto no meu inglês, então vai a resposta em português também)
Você pode monitorar o log para ter certeza, mas eu acredito que seu lazyPut está sendo removido da memória, porque a primeira página que chamou ele foi removida da memória. 
Apesar de parecer "singleton" ou uma espécie de "service locator", o gerenciador de instancias é altamente vinculado à página que o chamou, e se você remover ela da stack, ela será removida da memória. Get.find() não vai te dar uma instância nova, nem fazer uma cópia de uma instância, mas apenas criar um "atalho", para algum lugar, e esse lugar está salvo na memória, então quando você chama ele, você não tá criando uma instância, você tá basicamente fazendo um "Type get to => RealInstance". 
O problema é quando você usa uma instância pela primeira vez, o Get faz mais ou menos isso:
instancia Type registrada na memória, no caminho X, e a currentRoute dessa instância é Y. 
As regras são a seguinte:
1- Enquanto aquela instância está em primeiro plano, todos os serviços que precisar dela apontarão para o mesmo espaço em memória, e obterão a mesma instância. 
2- Se alguma rota "filha" (rotas que obtiveram push a partir daquela rota) precisar dela, e a rota principal ainda permanecer na stack, o Get entregará a mesma instância.
3- Se a primeira rota que usou aquela instância for disposada, a instância e todos os services ligados a ela serão disposados (sim, se você colocar um Service de API, e chamar ele do seu controlador, ele também será disposado, e não me pergunte como isso é feito, que eu terei que escrever um livro aqui). 
4- E o problema: Quando você registra um lazyPut, você não tá registrando uma instância. Você pode olhar o dart inspect, e você não verá qualquer instância daquele objeto na memória. Você está apenas registrando uma função, que se chamada, irá gerar uma instância. Essa função é armazenada temporariamente em memoria. Ela ocupa 16bytes (que é muito pouco, 100 delas daria 1,6kb, 100 mil delas daria 1,6mb). Mas partindo do pressuposto que nada que foi criado, e não seria mais usado permaneça na memória, ao criar a instância, no modo full, a função é deletada da memória. Eu sei, isso é totalmente irrelevante, e eu poderia muito bem manter essas fábricas na memória, mas não quero ver alguém fazendo benchmark inserindo 10 milhões de controladores na memória, removendo e dizendo que a aplicação ficou com 16mb a mais de lixo. É muito precipitado, mas a opção padrão remove as factorys para evitar isso. Então é muito mais fácil simplesmente usar o SmartManagement.keepFactory, e quando você precisar novamente daquela instancia, ela será fabricada e entregue a você novamente.

**Comment by marcobraghim** [comment]
That's right, it works

**Comment by novrizaledward** [comment]
hello ... 
how do you solve this problem? I found the same problem with you

**Comment by novrizaledward** [comment]
> That's right, it works

how do you solve this problem? I found the same problem with you
