### ISSUE TITLE
Type annotations for the arguments in Navigation

### ISSUE THREAD

**Issue by psycura** [jonataslaw/getx#332]
Firstly, i want to thank for this great library, that type of All-In-One solution for many common tasks in Flutter

**Is your feature request related to a problem? Please describe.**
I want to have possibility to pass different types of arguments and want to have an access to it in the common manner. 
For example i have function like this:
```
abstract class Args {
  bool isActive;
}
...
...
...
  static void open(Args args) {
    Get.toNamed(path, arguments: args);
  }
```

and somewhere in the widget i want to have an option to write something like this:
`  final bool isActive=Get.arguments<Args>.isActive;`
or at least
`  final bool isActive=Get.arguments<Args>['isActive'];`

Do you think it possible?

**Comment by jonataslaw** [comment]
Hi psycura, Dart does not allow typing of Get methods, so this is not possible.
I would have to turn the Get method into a function, and type the function as <T>, but that would involve breaking, since everyone would have to change Get.arguments to Get.arguments ().
This way it will not be possible, not in version 3, and it will last for a long time.
You can use cast to use Get.arguments directly.

final bool isActive=(Get.arguments as Args).isActive;

**Comment by psycura** [comment]
Thanks for reply.
I'll try the way you propose

**Comment by jonataslaw** [comment]
Well, closing this here, if it is possible to use types for get methods in the future, or if there is a break update where this can be inserted, I will reopen this.
