### ISSUE TITLE
Utility Classes from Stacked Architecture

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/getx#337]
**Is your feature request related to a problem? Please describe.**
I don't know if you've heard about the [stacked](https://pub.dev/packages/stacked) architecture, its awesome. 
As part of the package, you get these very nice utility classes like one that runs a future immediately the view is created, sets the view to busy while the data is being fetched, and then back to idle when the data is ready, and a lot more.

The package uses provider under the hood and so I tried my hands at making a version for Get. You can find it [here](https://github.com/Prn-Ice/get_only_example/blob/master/lib/core/viewmodels/base_controller.dart).

**Describe the solution you'd like**
I'd like to know if these classes could be added to Get.
You could run the entire app to see how this works and if you do consider it I'm available to help any way I can.

**Comment by jonataslaw** [comment]
I'm really impressed, you did a good job!
I do know Stacked, I have already made some PRs in the Stacked Services repository (which uses Get), but I never had the opportunity to use it personally, however much I wanted to try, because of the use of the Provider.
I can try to support Stacked, especially in the version you created, but I think it would be better to keep it maybe in a separate package, but anyway, that looks good.

**Comment by Prn-Ice** [comment]
Thanks for the feedback, FilledStacks also advised creating a separate package.

**Comment by NiranjanShah** [comment]
Hello, 

Believe the link provided is wrong 

"You can find it here <https://github.com/Prn-Ice/get_only_example/blob/master/lib/core/viewmodels/base_view_model.dart>.”

Regards,

Niranjan G Mandan

**Comment by Prn-Ice** [comment]
Yeah, I changed it.

**Comment by jonataslaw** [comment]
Well, if you want to work on it, you can create something like get_stacked, and I can even link it later in the readme.
I have no time to be able to dedicate myself to side projects for now, so I leave the possibility for you to continue with this, since you have done the job.
For now I'm closing this, but if you have any questions, I'll answer.
Perhaps other communication channels such as the gitter are more appropriate to discuss these issues as well. Thanks for working on it, it looks promising.

**Comment by Prn-Ice** [comment]
get_stacked, Just the name I was considering, I'll add the link here after I'm done publishing.

**Comment by Prn-Ice** [comment]
Its up now [here](https://pub.dev/packages/get_stacked)

**Comment by ghprod** [comment]
> Its up now [here](https://pub.dev/packages/get_stacked)

Amazing work! Thanks
