### ISSUE TITLE
Transition argument in toNamed

### ISSUE THREAD

**Issue by mdazharuddin1011999** [jonataslaw/getx#344]
Is it possible to add transition property to **toNamed** method as it is in **to**?

**Comment by jonataslaw** [comment]
Hi, I think that, at least logically, the transition on named routes should be inserted into GetPage statically.
It would not be difficult to implement this, but it would certainly bring unnecessary computational logic involved, basically before toNamed would have to copy the current route to a variable, remove the route from the list, give Get.addRoute (route with new transition)) and only then push the route. This is likely to have performance implications for larger applications, as well as evading an already established structure pattern. If someone else should take a project that you’re currently doing, they’ll know they’ll have to change the transition on the directions page. If you define this in your Get.toNamed, it will not know where to define the transition. I think it would mess up the code a bit, and it would make no sense (at least for me), to use Get.toNamed() in this situation, if Get.to() would have exactly the same behavior. I think that if you want to delegate the responsibility of defining transitions when pushing a route, you should use Get.to instead of Get.toNamed, because it was made for that and will have no performance implications. Named routes were created precisely to centralize and configure the behavior of the route in one place.
Therefore, my vote is not to implement this feature, first for structural reasons, and second for the cost benefit related to performance. This is not something that causes an application to freeze, but it is something that will clearly make ram consumption go up when pushing a route, especially in larger applications.
This may change in the future with navigator 2.0. But for now, this is my opinion on.

**Comment by mdazharuddin1011999** [comment]
Ok, no issues. Just wanted to know why it is not there. Thanks for explaining. Closing the issue.
