### ISSUE TITLE
How to use get to achieve route guards?

### ISSUE THREAD

**Issue by nothinggift** [jonataslaw/getx#372]
I tried to call Get.off in routingCallback, but only got an error.

**Comment by jonataslaw** [comment]
Route guards are not used on any top 20 sites, and in my view they are as close to a security vulnerability as possible.
As I work with this (security), I always get authorization from the Backend, and change the status of the scaffold body to the target data or display a "404 error" widget.
This is the approach that facebook, twitter and all other "safe" sites use (you are not redirected to a page, the page is opened and the link remains, but the "body" is only loaded after authorization, otherwise " body "displays" you are not authorized to access this ").
This forces you to have security always on your backend. But if you want to transfer responsibility for checking permissions for routes, you can ignore everything I said about security and do something like:

```dart
GetPages(
  page:(){
  if(GetStorage.read('admin')){
    return Admin();
  } else{
    return Home();
  }
}
```

I reiterate that this security is linked to web applications. Mobile guards are just syntactic sugar, since you cannot access something directly through a url.
For web I don't like the idea of ​​this page control by routes, and for me all addresses must be accessible, but only their content should be displayed after authorization, and you only have a route redirect when the route does not exist. This is how the most famous sites in the world behave, but if you just want to have route control, this example is useful and can be used for your project.
Sorry for the big text, I'm one of the most boring people in the world when it comes to security.

**Comment by nothinggift** [comment]
Thank you very much for your explanation. I agree with you very much, but the front-end route guards are very helpful to optimize the structure of authentication processing. In addition, we use hasura as the backend. Hasura is very easy to set user permissions, but it is difficult to customize error handling, so I need to determine what kind of error prompts should be given to the user on the front end, route guards will be very useful.

And How can I achieve this without using named routing?

**Comment by jonataslaw** [comment]
> Thank you very much for your explanation. I agree with you very much, but the front-end route guards are very helpful to optimize the structure of authentication processing. In addition, we use hasura as the backend. Hasura is very easy to set user permissions, but it is difficult to customize error handling, so I need to determine what kind of error prompts should be given to the user on the front end, route guards will be very useful.
> 
> And How can I achieve this without using named routing?

In the future I will insert a "lock" in buildPage, if a boolean function returns false. That's like, 2 lines of code. I just haven't added it yet because I have a certain resistance to guards, but if this is really important for the users' structure, I can implement it.

**Comment by nothinggift** [comment]
I really don’t consider flutter_web. I used auto_router before, but I don’t like code generators, named routes cannot provide effective code hints. In flutter, I didn’t find any advantages of named routes.

**Comment by nothinggift** [comment]
> if (allow) {
> Get.to(Page ());
> } else {
> OtherPage();
> }
OK, there seems to be no other way.
