### ISSUE TITLE
Removal of duplicate widgets/methods

### ISSUE THREAD

**Issue by MickelAngel0** [jonataslaw/getx#381]
I was going through documentation of getX package after seeing the state management using getX video.
In that video he showed the use of GetWidget

I found that there is similar method in getX package named GetView
Both GetWidget and GetView do the same task.
I saw there code 
Only method's names are different else both are completely same
I request the author @jonataslaw to remove such methods/widgets to avoid confusion

I don't know if there are other such methods or not 
But I found GetWidget and GetView are completely same
Please remove one of them.

**Comment by jonataslaw** [comment]
Initially GetView would be able to use more than one Controller.
But the final solution was "ugly", and I decided to comment on the code and not implement it.
I thought about deleting this, but users warned me that they used both for code organization, using GetView for Screens and GetWidgets for components.
That way, I can't remove either, because that would lead to some users breaking changes.
