### ISSUE TITLE
new worker : filter

### ISSUE THREAD

**Issue by peekpt** [jonataslaw/getx#423]
A worker to filter the incoming observer values, before it gets set :

 `filter(count, (counter)=> counter > 10 ? 10 :counter, active: true); // it only increments to 10`

` filter(text,(text)=> _capitalizeFirstLetter (text));  // some capitalize function`

"active" parameter (defaults to true)  is self explanatory, so we can enable/disable filter on the fly;

Obrigado por este magnífico package e Bom trabalho!

**Comment by jonataslaw** [comment]
Hi, workers already have conditions, which work as filters, and an "active" function doesn't make sense since you can assign "false" to the condition, and it will be temporarily disabled.

I'm not sure there would be any use in preventing a `setter`, it could be architecturally bad, because it's something like: Send the data anyway, anywhere, and it will be handled internally.
People will then leave

Sets should always be inside a Controller, and always inside a function, that will choose whether or not to update that variable, and I think that this feature can induce many people to make bad code, which is precisely the opposite objective of this package.
I will leave this issue open for 3 days, so if someone has a different opinion than mine, or who thinks I am wrong, manifest yourself in the comments, after all this lib is open source, and the community that will define your steps.

**Comment by jonataslaw** [comment]
My opinion remains the same, and considering that no one spoke out against me, I am closing this.
