### ISSUE TITLE
[Request] How to listen variable change in getxcontroller?

### ISSUE THREAD

**Issue by Ditway** [jonataslaw/getx#433]
here simple code.

thank you!!!

```dart
class Controller extends GetXController{

int count = 0;

@override
void onInit(){

this.addListenner((){
  
 print(this.count);

});

super.onInit();

}

void increase (){
  this.count += 1;
  update();   

}
void decrease(){
  this.count -= 1;
  update();   
}

@override
void close(){
 this.removeListenner((){});
 super.close();
}

}
```

**Comment by Nipodemos** [comment]
i don't quite understand your request, but here is not the place to ask questions about how to write correctly. The correct place is in the [Communication and support channels](https://github.com/jonataslaw/getx#communication-and-support-channels)

But since i am already here, maybe this is what you need: [Workers](https://github.com/jonataslaw/getx/blob/master/docs/en_US/state_management.md#workers)

By the way, where did you find those `this.addListener()` and removeListener? it is not anywhere to be found in documentation nor any issue posted here. With Getx you don't need that kind of boilerplate, is simple. You should pay a visit do state management documentation, there are several examples to help you start

**Comment by jonataslaw** [comment]
Please read the Workers documentation.
GetX does not work with changeNotifier to have addListener and removeListener methods.
Please use the support channels for questions. Github is exclusive for issues and requests for resources, and there are exclusive channels on the community platform for questions.
Before opening a resource request, please read the doc, and make sure that the resource does not exist.
As was answered, I am closing this.

**Comment by Ditway** [comment]
how way to listen none observe variable change?

because sometime  i dont use observable variable.

**Comment by jonataslaw** [comment]
If you want to listen variables, maybe there is no reason to use simple management.
I may even implement something like this in the future (I have no commitment to that statement), but I like to keep things well divided.
Simple management is very light because it is simple. Adding more features to it could add additional overhead for both (the reactive also uses GetxController), so I don't know if I want to do this.
