### ISSUE TITLE
Losing state of controllers in a List when item is removed

### ISSUE THREAD

**Issue by Andreigr0** [jonataslaw/getx#449]
When I create a `ListView` with creating for each element its own `GetxController` it works perfectly, but when I remove element from that list `GetBuilder` loses connection with that element where it was initialised even if `tagId` was set. It seems there is a bug:
<img src="https://user-images.githubusercontent.com/44437712/89416086-6e2e7b80-d735-11ea-8867-c5de70839ea0.gif" alt="Screen-Recording-2020-08-05-at-15 54 26" width="400"/>

<details>
<summary>Source code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:get/get.dart';

class ItemController extends GetxController {
  final TextEditingController textEditingController = TextEditingController();

  final String tag;

  ItemController({this.tag});

  bool isBusy = false;

  Future<void> setName() async {
    isBusy = true;
    update();
    await Future.delayed(const Duration(milliseconds: 500));
    print('Set name $tag ${textEditingController.text}');
    isBusy = false;
    update();
  }

  @override
  void onInit() {
    super.onInit();
    textEditingController.addListener(update);
  }
}

class Item extends StatelessWidget {
  final ItemController item;

  const Item(this.item);

  @override
  Widget build(BuildContext context) {
    return GetBuilder<ItemController>(
      init: item,
      tag: item.tag,
      id: item.tag,
      assignId: true,
      builder: (builder) {
        return Container(
          decoration: BoxDecoration(border: Border.all()),
          margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(item.tag),
              TextField(
                controller: item.textEditingController,
                onChanged: (_) => item.update(),
              ),
              const SizedBox(height: 10),
              RaisedButton(onPressed: item.setName),
              // ignore: unnecessary_string_interpolations
              Text('${item.textEditingController.text}'),
              if (builder.isBusy) const CircularProgressIndicator(),
            ],
          ),
        );
      },
    );
  }
}

class NestedInListView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Nested in list controllers')),
      body: GetX<NestedInListController>(
        init: NestedInListController(),
        builder: (model) {
          return ListView.builder(
            itemBuilder: (context, index) => Row(
              children: [
                Expanded(child: Item(model.items.elementAt(index))),
                RaisedButton(onPressed: () => model.deleteItem(index)),
              ],
            ),
            itemCount: model.items.length,
          );
        },
      ),
    );
  }
}

class NestedInListController extends GetxController {
  RxList<ItemController> items = <ItemController>[].obs;

  final List<ItemController> itemsGenerated = List.generate(100, (index) => ItemController(tag: 'index $index'));

  Future<void> deleteItem(int index) async {
    final item = items.removeAt(index);
    print('removed $item');
  }

  @override
  void onInit() {
    super.onInit();
    items.value = itemsGenerated;
  }
}
```

</details>

**Comment by Nipodemos** [comment]
Hello! 

"Id" is for when you are using nested navigation, which I guess you are not.

So, the first thing you need to do is remove the ID argument from your GetBuilders, but I don't think this will solve the issue

**Comment by jonataslaw** [comment]
Well, looking at your code right away, I see that you are messing up the indexes of a ListView, creating objects linked to a list index, and later deleting items from that list, causing the IDs assigned to the objects to be exchanged.
You have a list of items, each with a controller related to an ID.
You remove the item from the list, and I believe that you think this will be okay, but in vdd, when you remove an item from the list, you are assigning (value -1) to the index of the next item in the list, so the Controller will be attached to the item immediately after it was removed.
There is nothing wrong here, at least I could not identify an error in this code and in the example.
The behavior is the deletion of the next item, and then of the 2 items after, and so on, and that is the behavior of the code you created.
If you want to create a controller for each item in the ListView, you must use global: false, never IDs, because IDs do not make sense for the case in question.
Also the possibility to use Get.creator (instead of lazyPut) + GetWidget to do the same thing. The only thing you can't do is assign IDs related to a list, if your list is not immutable.

**Comment by jonataslaw** [comment]
Just so you can better understand what you did here, the moment you sent an ID by the builder, it won't change, so imagine that you sent the ID, 0, 1, 2, 3, 4.

You removed item 2, therefore, item 2 does not exist, controller 2 does not exist, but then the list became like this:
[0,1,3,4]

The position of index number 2 has a value of 3.
Now you click on the item to delete the index at position 2 and you are deleting item 3.

It is exactly what you are doing here.

Well, as this is not an issue involving Getx, but only programming logic, I am closing this.
