### ISSUE TITLE
Get.to() open class only first time

### ISSUE THREAD

**Issue by govindmaheshwari2** [jonataslaw/getx#475]
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I have added a Get.to() function inside a bottom sheet=>GestureDetector=>onTap. First time it will work and after getting back from the visited page it will not work. like only one time entry to that page. I have also added print("Tap") in onTap function and it is printing every time i click on it. 

**To Reproduce**
see code below

**Expected behavior**
open class on every time i tap on it.

**Flutter Version:**
latest

**Get Version:**
3.4.4

**Describe on which device you found the bug:**
ex: Samsung Galaxy M30S

**Minimal reproduce code**
onTap: (){
                          print("tap");
                          Get.to(DetailScreen(Image(image:CacheImage(answerList[answerList[index]["no"]]["answer"],scale: 2.0),)));
                        }

**Comment by Nipodemos** [comment]
hello!
the ideal of the minimal reproduce code is a piece of code that we can copy & paste in our machines and test to reproduce the error. 

Your code we can't reproduce because it has a lot of other classes which we don't have access.

You don't need to put every class in you code, just the minimal possible to reproduce your issue

**Comment by jonataslaw** [comment]
This is not a bug, it is a security feature to prevent the user from double clicking on the same page during a jank and creating duplicate pages
You can cancel this using the following configuration:

`Get.to(Page(), preventDuplicates = false);`
