### ISSUE TITLE
Devtools can't detect the app with GetMaterialApp

### ISSUE THREAD

**Issue by definev** [jonataslaw/getx#478]
[I](url) open devtool but i don't see any widget in details tree.

**Comment by Nipodemos** [comment]
Please follow the issue template when creating a new issue.
For example, we don't know which version of flutter or getx you are using
in this case you should also tell which IDE you are using and version of the extension

you should post too what tests have you done and what worked and what did not worked. For example, have you tested to replace GetMaterialApp to MaterialApp and then give an hot restart and see what happens?

have you tested if another app with getx gives the same error? have you tested if an app without getx gives the same error? this are all variables that we cant test here because it is happening specificly in your pc

**Comment by definev** [comment]
I restart my computer and it's gone! btw, Getx is awesome !!!
