### ISSUE TITLE
type 'String' is not a subtype of type 'RxString'

### ISSUE THREAD

**Issue by follow2vivek** [jonataslaw/getx#485]

**Comment by follow2vivek** [comment]
I'm not able to convert RxString to String.

**Comment by ghprod** [comment]
Use .value to get it

**Comment by djade007** [comment]
@follow2vivek don't declare your variable like this:
`String item = ''.obs;`

Rather do this:
`var item = ''.obs`
or
`RxString item = ''.obs`

**Comment by follow2vivek** [comment]
The process that I followed.

1. declared a variable 
var imageLink = ''.obs;
2. Hit API and got a new value.
imageLink = newValue;
3.Used Obx to update the widget
_controller.imageLink.value
_controller.imageLink.string
_controller.imageLink.toString()

I have tried all the 3 available options but still, I'm getting - type 'String' is not a subtype of type 'RxString'.

**Comment by jonataslaw** [comment]
declared a variable
var imageLink = ''.obs;

API call and got a new value.
imageLink.value = newValue; // Here

You need the ".value" to make a setter.
Please ask support questions on specific platform channels for this.
I recommend you use "final" instead of "var", this will prevent you from making mistakes like that, from trying to add the variable to an Rx without the .value.
As this is not a mistake, I am closing this.
