### ISSUE TITLE
`GetxController`의 해당 기능이 3.4.1 이후로 사라졌습니다.

### ISSUE THREAD

**Issue by idompolo** [jonataslaw/getx#507]
In GetxController
   Disposer addListenerId (String key, StateSetter listener) {
     _updatersIds [key] = listener;
     return () => _updatersIds.remove (key);
   }

Until version 3.4.1, all duplicate GetBuilders were updated even though the key values were duplicated.
Later versions only update the last created GetBuilder.

I am very in trouble now
I did a lot of coding with version 3.4.1.
It is a situation that needs change.
Please restore.

**Comment by Nipodemos** [comment]
but the Ids should be unique
But to be honest that's a clever idea to manage what rebuilds without giving an id for each and every GetBuilder
@jonataslaw have you changed something that made this issue happen?

**Comment by jonataslaw** [comment]
This would be possible if instead of Map, we had a Map<String, List <StateSetter>>.
This would bring a greater overhead, as the Ids would go through 2 loops.
This change was made in order to improve performance and build time, although I think it is a valid suggestion, I am not sure that this could not bring performance problems.
I'm going to do tests to make sure there is a less expensive way to do this.

**Comment by roipeker** [comment]
I understand the use case and _id_ maybe should be _uniqueId_. Otherwise is like a _groupId_. I agree with @jonataslaw and the overhead, it will apply to every GetxController.update()

I will try a workaround, although will increase the logic complexity of the updates, but avoid the forced double loop.

**Comment by roipeker** [comment]
Just pushed a PR for this issue (+ other improvements). Although is a big change, and i would like to have some feedback from @jonataslaw.
I ran my tests, and seems to be working fine, and is the most "performant" way i came up with (following @jonataslaw  reference that `HashMap` is faster to loop than `LinkedList`).
The update should be transparent to developers, no external API changed.

Just in case, [here is a quick code](https://gist.github.com/roipeker/f34654ca35b80f5bf34736bd865f6358.) to test the PR.

**Comment by Nipodemos** [comment]
This bug should also be fixed with this merged PR
@idompolo can you test it for us? but you need to wait for @jonataslaw to release the new version with this fix

If the problem persists, feel free to reopen this issue or create another one

**Comment by idompolo** [comment]
> 이 버그는 [# 565](https://github.com/jonataslaw/getx/pull/565) 로 수정되어야합니다.
> @idompolo 테스트 해 주시겠습니까? 하지만 @jonataslaw 가이 수정으로 새 버전을 출시 할 때까지 기다려야합니다.
> 
> 문제가 지속되면 언제든지이 문제를 다시 열거 나 다른 문제를 만드십시오.

Thank you very much. We will notify you again if any problems occur after testing.
