### ISSUE TITLE
PLAGIARISM CODE

### ISSUE THREAD

**Issue by agungnursatria** [jonataslaw/getx#509]
Hi Jonataslaw, 
I've seen that one of your file is copying my library without any notification on me ^^.

I know my plugin https://pub.dev/packages/regexpattern is an open source library where you can use it as you want. But what you have done is copying my code from https://github.com/agungnursatria/regexpattern/blob/master/lib/src/regex_pattern.dart to https://github.com/jonataslaw/getx/blob/master/lib/src/utils/regex/regex.dart with all the code is same as mine ^^.

Even if this is an open source library, please be more professional & appreciate the one creating this. thank you

**Comment by agungnursatria** [comment]
Please at least try to import the library. Not copying and make it as yours. Thanks ^^

**Comment by jonataslaw** [comment]
Ow, I initially apologize, I ended up taking this code snippet from a stackoverflow issue, and I am to blame for not researching snippets of the code to make sure it didn't come from a library.
Since the code is MIT, after the notification, I let you decide if you prefer the code to be removed from the library (or redone), or if you would like to add any copyright notice within the file containing your code.
And again, sorry about that, it definitely wasn't my intention.

**Comment by agungnursatria** [comment]
It's okay, just add it from import if you want to use it ^^

**Comment by Prn-Ice** [comment]
That's a bit harsh, I understand you must've put hard work into it but instead of having to add it to pubspec.yaml can't he just leave it in but with a reference to you at the top.

**Comment by agungnursatria** [comment]
Ok then but i'll be the one write it ok ^^

**Comment by agungnursatria** [comment]
i've seen your commit & i'll suppose this is closed ^^
https://github.com/jonataslaw/getx/commit/892b7504642acd1174a4153283c5b140ec0edf76

**Comment by jonataslaw** [comment]
Hi, thanks for letting us know.
As I had already written a library with most validations for over a year:
https://github.com/jonataslaw/media_utils

I decided to take advantage of most of the functions, and remove others that were not even linked to the code.
I apologize for the incident, and I think I was not the only one to copy code from a StackOverflow response, there are quite a few libs that use this, just searching for validators in the pub, the first result to appear is this:

https://github.com/FrazileDevelopers/FzRegex/blob/master/lib/utils/pattern.dart

I will search the question on StackOverflow, and warn that it is code from a library, so that your work is not copied ^^
And again, thanks for alerting.

**Comment by agungnursatria** [comment]
Hi @jonataslaw 

Wow, moreover this guys asking for donation from plagiarism code.

Thank you for informing me. I'll try to get my community to deal with this.

**Comment by marcglasberg** [comment]
@agungnursatria Sorry, I fail to see how he solved the problem. Did he import your library? Did he add a reference to you in the file? Did he add your name and linked to you in the README? Did he add your license to his license?

What has he done to fix the problem?

**Comment by jonataslaw** [comment]
The code mentioned was a file that had a regex of a StackOverflow question, and only the email methods, isApk, isImage, isMusic and etc. were used. The methods already had similar ones in MediaUtils (which did not use regex) and the email we used another one with support for Brazilian emails, and I just removed the dart file that had the code of the question, and warned about the stackoverflow issue, as well as other libs that the code had an author.
In his case, someone disseminated his proprietary code, so he was right to claim it, and nobody knew that the code for a question was copied, because it was given as a validation issue for StackOverflow.
