### ISSUE TITLE
[Question] Is it possible?

### ISSUE THREAD

**Issue by zl910627** [jonataslaw/getx#512]
![image](https://user-images.githubusercontent.com/53897531/91364405-3779eb80-e831-11ea-9c3b-44fc137a2489.png)

According to the image above, reactive state management can be used without defining the controller separately.
I would appreciate it if you could let me know if this is possible.

**Comment by jonataslaw** [comment]
It's possible. 
It is not a good practice, but it is perfectly possible

**Comment by zl910627** [comment]
Another question, what is different between `GetView` / `GetWidget` , and recommended use case ?

**Comment by jonataslaw** [comment]
Use GetView.
GetWidget is for a specific context where you have lists, and you want to have a controller for each item. In this case, instead of using GetView with Get.put / lazyPut, you use GetWidget with Get.create ().

GetView is simpler, it's just a StatelessWidget, GetWidget caches the controller, so it can be used with Get.create, you may not need it.

Please try not to use the issues field to ask questions, join one of the community channels, where you will have a quicker response, in addition to being the appropriate channel for that. This space is reserved for issues and requests for resources, so I'm closing this.

**Comment by Nipodemos** [comment]
@jonataslaw i remember that some time ago, GetWidget was exactly the same as GetView.

When the breaking change happened? I looked a bit on changelog but i didn't found anything commenting on that

**Comment by jonataslaw** [comment]
Actually, there was no breaking change, but a cache was added to GetWidget to make use of Get.create().
I think this should be documented, but I still think about tinkering with this API, because onInit and onClose are not called when Get.create is used.
I think the change was so small that I ended up forgetting to document and insert it on ChangeLog, sorry.
