### ISSUE TITLE
Use regular Snackbars instead of this seemingly custom implementation

### ISSUE THREAD

**Issue by CiriousJoker** [jonataslaw/getx#554]
**Is your feature request related to a problem? Please describe.**
I don't want to use the modern snackbar, it doesn't fit the style of the app and restyling it defeats the purpose of using Get for simplicity.

My snackbar is a single line, no message, just title.

**Right now I'm using this code:**

```
      final snackbar = SnackBar(
        content: Text("My message"),
      );
      Scaffold.of(context).showSnackBar(snackbar);
```

**Describe the solution you'd like**
```
      Scaffold.of(Get.context).showSnackBar(snackbar);
```

This could be implemented via `GetScaffold()`, similar to `GetMaterialApp()`.
This would allow for much greater compatibility with other Scaffold "native" calls as well.

**Describe alternatives you've considered**
Couldn't come up with any other than passing around the snackbar's context manually

**Comment by jonataslaw** [comment]
The Get context is immutable, and it is a NavigatorState context, not a ScaffoldState context as required by the snackbar.
If the modern snackbar doesn't fit your pattern, you can use Get.rawSnackbar, which is made with Material.
Unfortunately, even adding a GetScaffold, this would not be possible, unless they created other functions like Get.nativeSnackbar().
I'm not sure this would be useful, as it would add another Widget to get what you already have with rawSnackbar today.
However, I will leave this resource request for 2 days to see if this resource is supported by the community, otherwise it will be closed until some collective interest is expressed in it.

**Comment by CiriousJoker** [comment]
It turns out it's not as important even for me after all. I wrote a helper method that applies the correct styling manually.
