### ISSUE TITLE
Is there an actual Getx widget

### ISSUE THREAD

**Issue by mtkgeek** [jonataslaw/getx#562]
This is not really an issue with the package but i must say it's been bugging me. Is there an actual `Getx` widget. I know we have the `Obx`, `Getbuilder` and even `MixinBuilder` but i have never really come across the "Getx" widget even in the state management documentation. 
I've heard it mentioned a couple of times on different tutorials and have even stumbled on some obsolete readme that makes a reference to it but haven't really seen it actually used. 
Some clarification would be great. Thanks.

**Comment by Nipodemos** [comment]
yes there is 👍 
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#using-the-values-in-the-view
And it behaves exactly like GetBuilder, but for obs values

i usually help with documentation here so could you tell where did you find that obsolete readme? if it was here in getx repository, then you could point it out to me so i can fix in my spare time 😄

**Comment by jonataslaw** [comment]
GetX is used to initialize controllers with the "init" property if you are not using bindings.
GetX is used to access properties of other controllers.
Let's say you are in a View, which has its controller, for example, Home, and HomeController.
You need the UserController to retrieve the user's name.
You can wrap the widget in a GetX, so if the user changes the name in settings, the name will be changed in the welcome screen.

```dart
class UserController extends GetxController{
String name = "Jonny"
}

class HomeController extends GetxController{
final posts = <Posts>[];
[...]
}

class HomeView extends GetView<HomeController>{

build(context){

return Column(children:[
GetX<UserController>(builder:(userController) => Text("Welcome ${userController.name}")),
Listview.builder(
itemCount: controller.posts
[...]
])
}

}

```

Since this is not a feature request or bug description, and has been answered, I am closing this.

**Comment by mtkgeek** [comment]
> yes there is 👍
> https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#using-the-values-in-the-view
> And it behaves exactly like GetBuilder, but for obs values
> 
> i usually help with documentation here so could you tell where did you find that obsolete readme? if it was here in getx repository, then you could point it out to me so i can fix in my free time 😄

Hi, i don't really think it's an issue with github. Probably a relic on google's index. To be honest i really can't say i remember specifically how i got to that page 😅. Thanks for your help anyways
