### ISSUE TITLE
Themes don't work properly on web applications

### ISSUE THREAD

**Issue by devkarim** [jonataslaw/getx#594]
**Describe the bug**
Created a button to enable/disable dark mode however I have to press it twice to actually take effect for some reason. Another thing I noticed is that ThemeMode.system as default makes it worse, I tried debugging and noticed that isDarkMode is false even though it was initially set to dark mode. The last thing is ```Get.theme``` doesn't properly change in all widgets when I change the theme mode.

**To Reproduce**
1. Set the initial themeMode to ThemeMode.system.
2. Try to change theme mode.

**Expected behavior**
I think Get.theme should be changed once the theme mode is changed plus isDarkMode needs to be also changed on initialization depending on ThemeMode.system.

**Screenshots**
The appbar's background color should be the same color as the scaffold's background but it is not: https://prnt.sc/uf6w4y

**Flutter Version:**
1.21.0-9.2.pre

**Getx Version:**
3.10.2

**Describe on which device you found the bug:**
Chrome

**Minimal reproduce code**
```dart
IconButton(
   icon: Icon(Icons.brightness_3),
   iconSize: 20,
   color: Get.isDarkMode ? Colors.white : Colors.black,
   onPressed: () => Get.changeThemeMode(Get.isDarkMode ? ThemeMode.light : ThemeMode.dark),
 ),
```

**Comment by roipeker** [comment]
@devkarim In my tests on `1.22.0-9.0.pre` (i'm on dev branch) and latest GetX is working fine, and I didn't have issues with Theme in the past.

First of all, for the Theme mode to work (even with MaterialApp), you need to define both Themes in the constructor.

```dart
GetMaterialApp(
      themeMode: ThemeMode.system,
      darkTheme: ThemeData.dark(),
      theme: ThemeData.light(),
      /// ... other initializations.
    );
```

To change the color in your example, you need to make use of `InheritedWidget`, so that Flutter knows that your Widget has to rebuild when you change the Theme. This applies to `MediaQuery.of()` as well, if u wanna validate if brightness, size or any other capability changes....
 
So, you have 2 options:

1 - You read the Theme from the context, and get the brightness from there ... That will make `Theme.of(context)` mark this widgets (under this build() function) as "dirty", and rebuild them when a Theme property changes.

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
            icon: Icon(Icons.brightness_3),
            iconSize: 20,
            color: context.theme.brightness == Brightness.dark
                ? Colors.white
                : Colors.black,
            onPressed: () => Get.changeThemeMode(
                Get.isDarkMode ? ThemeMode.light : ThemeMode.dark),
          ),
        ],
      ),
    );
  }
```

Or you just use the `context.theme` "getter", that internally calls `Theme.of( context )`, so it will also mark the child Widget to rebuild when a `Theme` property changes:

```
  @override
  Widget build(BuildContext context) {
    context.theme; /// just put the line here and will subscribe to changes.
    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
            icon: Icon(Icons.brightness_3),
            iconSize: 20,
            color: Get.isDarkMode ? Colors.white : Colors.black,
            onPressed: () => Get.changeThemeMode(
                Get.isDarkMode ? ThemeMode.light : ThemeMode.dark),
          ),
        ],
      ),
    );
  }
```

**Comment by devkarim** [comment]
Ohh my bad, never noticed that. Thank you! Sorry for any inconvenience.
