### ISSUE TITLE
[Feature Request] A GetView that initialize the controller if it's not already initialized

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/getx#610]
**Is your feature request related to a problem? Please describe.**
Is not a problem, just a suggestion

**Describe the solution you'd like**
After I read #609 suggestion, I thought about that. It seems like an ideal place to initialize the controller in case you are using only one controller per view, which is the recommended way of doing it.

**Describe alternatives you've considered**
The ways today of doing it are: 
* using `init:` in `GetBuilder` or `GetX` Widgets, which is fine, but the fact that you can only initialize once and doing that wrong can lead to errors that are hard to find confuse a lot new users of Get.
* Using Bindings: This way is ideal when the user has something else to initilalize other than a controller, but if it's just that, is just one more file that increase the complexity of the app (instead of having a file for view and other for controller, you have a file for view, for binding and for controller, three files per view)
* declaring it on the view: this is fine and i think is very simple and efficient, but sometimes the user initialize the controller in the build method, instead of the class, which cause that problem of the controller being initalized every time the view re-render and being hard to track the error. To be honest this one is a minor inconvinience, is not bad.

**Drawbacks of this solution**
* New users may still be confused by the fact that it is not clear where the controller is being initialized, without mention the use-cases when it needs a controller per widget, or when they use `global: false`. But it is something I am willing to accept.
* If more than one controller is needed in a view, the user will have to initialize one and use GetView for other, which will be kinda odd and maybe confusing. 

Well, @jonataslaw I want to hear your opinion about that, and if possible, to build it 😅 . I don't know how to do it myself

**Comment by roipeker** [comment]
I know the topic is about the "scope" of the controller and confusion with docs.
You can not create an instance of a class, based on the Generics <Type>, so automation regarding that is impossible.
I think the issue is not about "bindings" scope, as it obviously exists for the reason of initializing controllers for a specific GetPage view (Route).
Declaring `Get.lazyPut(() => Controller(), fenix:true);` before `GetMaterialApp()` or inside `GetMaterialApp.onInit: ()` might have a similar effect as `Bindings`, but we can not restrict WHERE an instance is created.

**Comment by jonataslaw** [comment]
It is not possible to create instances of a generic, so it is impossible to create an instance of a controller by passing a type.

The only way to do this with dart (without any exception), would be to pass the controller instance in the constructor with a super, but I think this can be more difficult for beginners than using Bindings.

After all this time, I personally still think that the best way to manage instances and dependencies is to use Bindings together with GetView.
I believe it is the clearest way to say:
I started the `controller` within the `binding` of this `route`, and this `view` is controlled by this `controller`.
GetX allows many approaches to make it easier for people to start and already have some code working, and they will mature and use library resources that provide cleaner code over time.
Starting with "Get.put" or "init" is the easiest and most understandable way for a beginner.
However Bindings manage to make the code cleaner and more readable than anything else, because you know which dependency was created, which route it belongs to, and you can initialize it in a Lazy way in the view, preferably with a GetView.
The most recommended way, for medium and large projects, is to use Bindings.
This does not mean that using Get.put in the view, or the init in GetX / GetBuilder are bad approaches, but that the code created with Bindings is much better and more readable.

**Comment by Nipodemos** [comment]
well dart don't support that is just disappointing 😞 
Even so, thank you @roipeker and @jonataslaw for clarifying for me
