### ISSUE TITLE
 overwrite in Widget extensions

### ISSUE THREAD

**Issue by alexkharech** [jonataslaw/getx#631]
**Describe the solution you'd like**
What if you create an extension that extends Widget and wraps it in Obx in the builder?

**Comment by alexkharech** [comment]
is there a noticeable difference in memory consumption if we wrap all the widgets?

**Comment by jonataslaw** [comment]
Unfortunately because it contains a Builder, it is not possible to use extensions with it. Reactivity will not work.
I've tried this before, something like: Text("controller.name"). Rx, but unfortunately before being sent by extension, controller.name is serialized in String, and therefore loses reactivity.

In dart, the only way to preserve the type by going through a parameter, and putting it inside a function, that is why GetBuilder has a Builder, and Obx receives a widget function as a parameter.
