### ISSUE TITLE
Adding get_storage into the package

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#637]
I notice that the package has been split into multiple small packages. In that case, can I request to add get_storage as one of the packages as well? 
Thanks.

**Comment by Nipodemos** [comment]
@jonataslaw explained this a long time ago. he does not want to do that because right now, getx does not need anything to work, and it works in all platforms. GetStorage in the other hand does not work in all platforms, as it needs something more to be able to store and read data. Also I think there is more dependencies, and the package would be bigger with something that most people will not use

jonatas can explain this better than me.

**Comment by jonataslaw** [comment]
would like to insert get_storage in get, but I still don't for some reasons:
1- get_storage depends on "path_provider" which is a Flutter package. getx tries to remain oblivious to any external package to ensure its stability. There is no possibility for an external package to break getx, because it does not have external packages, and as much as path_provider is maintained by the flutter team, it breaks and causes incompatibility with pana at times, which would lower the package's rating in the pub for literally nothing.
2- If you add Getx to your project, you will see that the file size remains the same. If you use everything from getx, it will increase your final application by a maximum of 100kb. Get_storage alone would not increase the application by 2kb, but path_provider can increase by having native dependencies, so I am concerned with that too.
3- Get_storage work on android, ios, web, linux and mac, and you need another package ("path_provider_windows") to work on windows. Getx works on any platform, from android, ios, web, linux, mac, windows, even on servers.
4- Maybe, I create something like "get_full", but I'm not sure if this is desirable for users, if it is, I do.

**Comment by jasonlaw** [comment]
All I need from get_storage is just to store some simple settings value, if that is achievable with "get_full", it would be very great. :)

**Comment by Nipodemos** [comment]
create a second package that is everything merged will confuse people even more
it will already be hard to explain that GetX is a set of packages

**Comment by roipeker** [comment]
Good idea.
In order to prevent the usage of the external dependency, you could change the default constructor to force devs to choose the root directory where files will be. Unless i'm missing something, would be a nice addition to have "out of box" :P with getx.

**Comment by n8crwlr** [comment]
> All I need from get_storage is just to store some simple settings value, if that is achievable with "get_full", it would be very great.

Makes no sense. Just use both packages

**Comment by Nipodemos** [comment]
Closing since it is resolved
