### ISSUE TITLE
Route arguments not receiving

### ISSUE THREAD

**Issue by mohanhari** [jonataslaw/getx#691]
If we use Get.snackbar after any route code like Get.toNamed('/something', arguments: 'this is an argument'), the arguments are not receiving in the controller. Put if we pass as parameter it's working perfectly

**Reproduction code

Get.toNamed('/any_page', arguments: 'this is a argument);
Get.snackbar(titleText, bodyText);

**To Reproduce**
Steps to reproduce the behaviour:
1. use Get.snackbar after any get route call with argument like 'Get.toNamed('/any_page', arguments: 'this is a argument)'
2. you will note that arguments are missing the next page
3. if you use snack bar before the get route call arguments will be receiving

**Expected behaviour**
It expected to receive arguments in the next page

**Flutter Version:**
Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-IN)
    • Flutter version 1.20.4 at /Users/mohans/workspace/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

**Getx Version:**
3.12.1

**Describe on which device you found the bug:**
ex: Iphone 11 pro max

**Comment by eduardoflorence** [comment]
I believe this is the expected behavior. It should not be a good practice to place a snackbar after navigating to a route due to the screen transition.
Why don't you put Get.snackbar in the Controller onInit of "/any_page"?

**Comment by mohanhari** [comment]
@eduardoflorence I know its not good practice but is it expected to not receive arguments?. Even its a bad practice shouldn't snack bar get affected rather than route arguments as the route call is made first, it should be working fine and as snack bar gets called next it should show an error instead of the arguments go missing. wouldn't you agree?

**Comment by eduardoflorence** [comment]
@mohanhari 
I did a test with and who is getting the argument is the snackbar. You can test it like this:
`Get.snackbar ('title', Get.arguments);`
This is because there was no time for the route to be loaded and the snackbar is executed first. You could solve it like this:
```dart
myMethod () async {
   await Get.toNamed ('/any_page', arguments: 'this is a argument);
   Get.snackbar (titleText, bodyText);
}
```
Now any_page will receive the arguments correctly, but snackbar will not appear, as we are already on another route, so that's why I thought it was a bad practice.
I'm sorry for my English.

**Comment by Nipodemos** [comment]
This is expected behaviour.

Everytime you push a new route, the `arguments` parameter is replaced by what the route put in there. When is empty, the arguments becomes empty also.

Since you are not awaiting, by the time you will access the arguments, it has it's value already overriden.

@eduardoflorence suggestion is a good one, if you want to follow.

If you want this behavior to be different in GetX, feel free to open a new issue detailing your feature request, and jonatas will see what he can do.
