### ISSUE TITLE
Issue using RXList and child widgets

### ISSUE THREAD

**Issue by omartinma** [jonataslaw/getx#738]
When using child widgets and observables there is something weird.

With this code, everything is working fine, but getting a warning "The member 'value' can only be used within instance members of subclasses of 'package:get/get_rx/src/rx_iterables/rx_list.dart'"

```dart
return Obx(() {
      return _RoastersSection(
        roasters: Get.find<RoastersController>().triedRoasters.value,
      );
    });
```

If I remove .value as the warning suggest and I use directly the observable, then is throwing an error 
"[Get] the improper use of a GetX has been detected. You should only use GetX or Obx for the specific widget that will be updated."

RoastersSection is just a column with Text and Listview without any GetX component. If I use there any Obx will throw an error as well as I am not using any observable inside, just the list.

**Flutter Version:**
1.20.2

**Getx Version:**
3.13.2

**Comment by jonataslaw** [comment]
Please read the documentation, you cannot use .value with Iterables (Lists, Maps, Sets)

**Comment by omartinma** [comment]
> Please read the documentation, you cannot use .value with Iterables (Lists, Maps, Sets)

Yes, I read the documentation, thats why I am openning this issue because as you can see in my comment if i remove .value as susggested in the documentation the error is displayed.

**Comment by jonataslaw** [comment]
> > Please read the documentation, you cannot use .value with Iterables (Lists, Maps, Sets)
> 
> Yes, I read the documentation, thats why I am openning this issue because as you can see in my comment if i remove .value as susggested in the documentation the error is displayed.

An error is shown because you are using an Obx for a context where it should not be used (I believe that the red screen that I insert explains well what happened). Obx is used to build widgets, you are passing a List by parameter, there is no need to use an Obx in this scenario.
I know that the documentation can be extensive, but there are community channels where you can get your questions answered more quickly, this channel is for reporting bugs, or making suggestions for improvements, so I suggest you join a community channel to answer your questions about use.

**Comment by omartinma** [comment]
> > > Please read the documentation, you cannot use .value with Iterables (Lists, Maps, Sets)
> > 
> > 
> > Yes, I read the documentation, thats why I am openning this issue because as you can see in my comment if i remove .value as susggested in the documentation the error is displayed.
> 
> An error is shown because you are using an Obx for a context where it should not be used (I believe that the red screen that I insert explains well what happened). Obx is used to build widgets, you are passing a List by parameter, there is no need to use an Obx in this scenario.
> I know that the documentation can be extensive, but there are community channels where you can get your questions answered more quickly, this channel is for reporting bugs, or making suggestions for improvements, so I suggest you join a community channel to answer your questions about use.

1-That error is the same you are displaying when there is not obs value used at all, what is not the case in that example. And yes, there is a need for obx to be used there, as _RoasterSection is used in 2 places, both with different origin controllers, so i can not use the Obx inside the child. So this widget need to be rebuilt whenever there is a change in the list so I dont understand why you say is not needed.
2-You assuming I didnt ask before in community/forum what I already did and nobody knew the answer so thats why i thought here would be the best way to know if it was a bug or wrong use in my side.
3-I can understand your concerns about my knowledge of the documentation if I create many issues in the repository, but closing me 2 issues in the same day telling me the same answer without even analyzing I think is not the best way to proceed if you want to help the community to understand your package specially when there is not so many examples/documentation about.

**Comment by jonataslaw** [comment]
What's inside _RoastersSection?
If you provide a minimum reproduction code I can help you to analyze what is wrong, even if this is not the appropriate place for it.
Note that members can mention me on the platform channels for something unsolved, and it is still preferable to open issue on github for a support issue.
The list is not being accessed, because there is no property of it being used. If you use a list.lenght, list.anything, the error will not occur.
If you need dynamic lists, the right way is a ListView.builder, not a column.
Note that the two closed issues were yours, and on support issues. If you ask me how to do A or B with the library, I, and thousands of other users will respond. But asking how to do A in your code, in your custom class (that you didn't even insert the code here), this channel is completely inappropriate for that. I hope you understand.

**Comment by omartinma** [comment]
> What's inside _RoastersSection?
> If you provide a minimum reproduction code I can help you to analyze what is wrong, even if this is not the appropriate place for it.
> Note that members can mention me on the platform channels for something unsolved, and it is still preferable to open issue on github for a support issue.
> The list is not being accessed, because there is no property of it being used. If you use a list.lenght, list.anything, the error will not occur.
> If you need dynamic lists, the right way is a ListView.builder, not a column.
> Note that the two closed issues were yours, and on support issues. If you ask me how to do A or B with the library, I, and thousands of other users will respond. But asking how to do A in your code, in your custom class (that you didn't even insert the code here), this channel is completely inappropriate for that. I hope you understand.

So basically Obx need to be used inside _RoastersSection(it is just a container with Title and ListView). I tried so and it is working but I feel it 'weird' to be used in the child(where doesnt know anything about controllers, just get a list and paint it) and not in the parent who is accessing the controller and the obs value itself.

Thanks for the help and sorry for the inconvenience, but please again if you can tell me a channel more appropriate for these kind of discussion I would really like to join as I'm creating content for my local community and lately I'm using GetX for that content :)
