### ISSUE TITLE
Get.offAll() closes a page before it is loaded up

### ISSUE THREAD

**Issue by john-eleos** [jonataslaw/getx#826]
having 2 pages Page1 and Page2, when I call Get.offAll(Page2()), it calls the onClose() function in Page2 controller before the page is loaded,using Get.offAllNamed("pageb"), is how I was able to escape this error

**Comment by jonataslaw** [comment]
Please, provide a reproduction code

**Comment by ELEOS-MAP** [comment]
// first ui 
class FirstUi extends StatelessWidget{
  final FirstUiController reg = Get.put(RegisterController());
}

// first ui controller function i call the Get.offAll() in

  reg() {
    Get.offAll(SecondUi());
    update();
  }


// second Ui

class SecondUi extends StatelessWidget{
  final SecondUiController emailVerify = Get.put(SecondUiController());
}



// second ui controller 

class SecondUiController extends GetxController{
   TextEditingController pin;
   StreamController<ErrorAnimationType> errorController;


     @override
  void onInit(){
    pin = TextEditingController(text: "");
    errorController = StreamController<ErrorAnimationType>();
    super.onInit();
  }

  @override
  void onClose(){
    pin?.dispose();
    errorController?.close();
    super.onClose();
  }
}


//  what happens when  reg() is called 

[GETX] "SecondUiController" has been initialized
[GETX] GOING TO ROUTE /SecondUi
[GETX] REMOVING ROUTE firstui
[GETX] REMOVING ROUTE /
[GETX] "FirstUi" onClose() called
[GETX] "FirstUiController" deleted from memory
[GETX] "SecondUiController" onClose() called
[GETX] "SecondUiController" deleted from memory

// Error when TextEditingController pin is called



════════ Exception caught by foundation library ════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for FocusNode:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:292:5)
#4      TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:175:11)
...
The FocusNode sending notification was: FocusNode#71170([PRIMARY FOCUS])
  context: EditableText-[LabeledGlobalKey<EditableTextState>#68403]
  PRIMARY FOCUS
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
A TextEditingController was used after being disposed.
The relevant error-causing widget was: 
  PinCodeTextField file:///Users/cosmas/AndroidStudioProjects/talos/lib/view/auth/verification/email_verification.dart:56:21
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
'package:flutter/src/rendering/object.dart': Failed assertion: line 2377 pos 12: 'attached': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by bbrazsilveira** [comment]
> having 2 pages Page1 and Page2, when I call Get.offAll(Page2()), it calls the onClose() function in Page2 controller before the page is loaded,using Get.offAllNamed("pageb"), is how I was able to escape this error

I had the same issue. In my case, Firebase wall firing auth event twice and my app was calling Get.offNamedAll twice as well, so it causes the deletion of the last controller.

**Comment by eduardoflorence** [comment]
Hi @john-eleos, when you use unnamed routes and StatelessWidget, Get.put must be called within the build method. Do this and it will solve the problem.

```dart
// first ui
class FirstUi extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
    final FirstUiController reg = Get.put(RegisterController());
    return ...
  }
}

// second Ui
class SecondUi extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
    final SecondUiController emailVerify = Get.put(SecondUiController());
    return ...
  }
}
```

**Comment by jonataslaw** [comment]
I cannot reproduce this in the latest version.
If you still see the problem, follow what was suggested by Eduardo, or use the new syntax Get.offAll (() => Page ()), this will solve any problem of misaligned dependencies

**Comment by nauhalf** [comment]
Hi @john-eleos . I think I know where the problem is. I use PinCodeTextField too. In that class, it has a property `autoDisposeControllers` with default value `true`. so the PinCodeTextField first dispose your `TextEditingController`, and when the getx controller call `onClose`, the TextEditingController call dispose again and it became an error
