### ISSUE TITLE
[GetConnect] MultipartFile read from filepath

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#830]
Hi,

Is the MultipartFile able to read file from filepath? If not, can this be added as a feature?
Btw, I tried to use the code from dio to read the file from filepath, however, this seems not possible since the Multipart in Getx is not taking stream for bytes. Can we have a constructor that takes stream as argument?

Thanks.

**Comment by jonataslaw** [comment]
Use `File(filepath).readAsBytesSync()` to get bytes from file.

Getting a path file may be supported in the future, but I don't like this feature personally, since it only works on a mobile device.
Sending bytes is a universal solution, and has automatic integration with Imagepicker, where pickedFile delivers the file bytes directly, but in the future I can add the fromFile and fromString method for those who do not want to have their application running on the web, only on mobile.

**Comment by jasonlaw** [comment]
Thanks for the advice, this should works for me.
Btw, I found that the FormData is not really working with GetConnect, I am trying to migrate from existing dio with GetConnect, get stuck with those required FormData.
Hope these issues are fixed as soon as possible, so we can have more time to test our app with GetConnect implementation, due to the FormData issue, we have to still stick with Dio.

**Comment by jonataslaw** [comment]
> Thanks for the advice, this should works for me.
> Btw, I found that the FormData is not really working with GetConnect, I am trying to migrate from existing dio with GetConnect, get stuck with those required FormData.
> Hope these issues are fixed as soon as possible, so we can have more time to test our app with GetConnect implementation, due to the FormData issue, we have to still stick with Dio.

I am using the latest version in a application real with multipart.
Can you confirm that this works for you?
I ended up simplifying the api, and for me it works well, but I would like to know if other people are experiencing any problems with multipart request.

**Comment by jonataslaw** [comment]
Added on 3.22

**Comment by jasonlaw** [comment]
The FormData issues are fixed with the latest version, however, we encountered other errors, will report the issue if confirmed it is a bug in the package. Thanks!
