### ISSUE TITLE
route like A-B-A, Page A getController be null

### ISSUE THREAD

**Issue by TomVista** [jonataslaw/getx#909]
### log
```
[GETX] "GetMaterialController" has been initialized
[GETX] "SplashController" has been initialized
I/ExoPlayerImpl( 4627): Init b78a6f4 [ExoPlayerLib/2.11.7] [generic_x86_arm, AOSP on IA Emulator, Google, 28]
I/OMXClient( 4627): IOmx service obtained
I/ACodec  ( 4627): codec does not support config priority (err -2147483648)
I/flutter ( 4627): ferry link create
I/flutter ( 4627): token null
[GETX] REPLACE ROUTE /
[GETX] NEW ROUTE /SignupScreen
[GETX] "SignupController" has been initialized
[GETX] "SplashController" onClose() called
[GETX] "SplashController" deleted from memory
D/AudioTrack( 4627): stop() called with 219456 frames delivered
[GETX] GOING TO ROUTE /SigninScreen
[GETX] "SigninController" has been initialized
[GETX] GOING TO ROUTE /SignupScreen
[GETX] REMOVING ROUTE /SigninScreen
[GETX] REMOVING ROUTE /SignupScreen
[GETX] "SigninController" onClose() called
[GETX] "SigninController" deleted from memory

```
* into Splash
* ``Get.off`` SignupPage
* ``Get.to`` SigninPage
* ``Get.offAll`` SignupPage

then GetController of SignupPage is null

**Comment by eduardoflorence** [comment]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
A clear and concise description of what the bug is.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
void main() => runApp(MaterialApp(home: Home()));

class Home extends StatelessWidget {
  final count = 0.obs;
  @override
  Widget build(context) => Scaffold(
      appBar: AppBar(title: Text("counter")),
      body: Center(
        child: Obx(() => Text("$count")),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => count.value++,
      ));
}
```

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Flutter Version:**
Enter the version of the Flutter you are using

**Getx Version:**
Enter the version of the Getx you are using

**Describe on which device you found the bug:**
ex: Moto z2 - Android.

**Comment by TomVista** [comment]
see code at [getx_test](https://github.com/TomVista/getx_test)

### bug 



getxController be null

### Reproduce step

* click ``to other page`` button
* click ``offAll to my home page`` button 

![42112](https://user-images.githubusercontent.com/42435611/102292999-348e3c80-3f81-11eb-854c-22b813c569de.gif)

### flutter doctor
```dos
PS C:\WINDOWS\system32> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.685], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.0)
[√] Connected device (1 available)

• No issues found!
PS C:\WINDOWS\system32>
```

### get version
```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  get: 3.23.1
```

**Comment by TomVista** [comment]
i find
#701 
may be same reason
