### ISSUE TITLE
[GetConnect] Use use UTF-8 as default decoding

### ISSUE THREAD

**Issue by Joluall** [jonataslaw/getx#929]
I tried to convert to UTF-8 the responce of my API, just like I do with http, but it doesn't work.

With http I do this

`var response = await http.get(
          "url");
      var responseJson = jsonDecode(utf8.decode(response.bodyBytes));`

When I try to do the same with GetConnect:

`Future<List<User>> getUsers() async {
    final Response response = await _dbProvider.get(
      'user',
    );

    final responseJson = json.decode(utf8.decode(response.bodyBytes));

    return (responseJson as List).map((e) => User.fromJson(e)).toList();
  }`
Give me the error: "The argument type 'BodyBytesStream' can't be assigned to the parameter type 'List<int>'.

And if I do:

`Future<List<User>> getUsers() async {
    final Response response = await _dbProvider.get(
      'user',
    );

    final responseJson = json.decode(utf8.decode(response.body));

    return (responseJson as List).map((e) => User.fromJson(e)).toList();
  }`

The console print this error: "I/flutter ( 4640): type 'List<dynamic>' is not a subtype of type 'List<int>'

My JSON is like this:

`[{"id":1,"name":"Alejandro González Iñárritu"]`

But with GetConnect I get:

`[{"id":1,"name":"Alejandro GonzÃ¡lez IÃ±Ã¡rritu"]`

So, UTF-8 decoding is better I guess

**Comment by sc-ot** [comment]
Hey, had the same problem with umlauts. I think this is a good idea.

**Comment by eduardoflorence** [comment]
Hi @Joluall, GetConnect uses the encode described in its header. check in your API response header if the Content-type key looks like this:
`Content-type: application/json; charset = utf-8`
If it is just like this:
`Content-type: application/json`
The default encode is latin1, so you must do:
latin1.decode(response.bodyBytes)

In your second example, using response.body, there is no need to do `json.decode`, because GetConnect already does this for you and returns you a list:
```dart
final responseJson = response.body;
return List<User>.from(responseJson.map((e) => User.fromJson(e)));
```

**Comment by 1774575836** [comment]
In Getx 4.1.4 version utf8 decoding is not used. Have to call jsonEncode then call jsonDecode(utf8.decode(newbody.runes.toList())) to correct decode utf8 runes.

**Comment by jonataslaw** [comment]
Fixed by https://github.com/jonataslaw/getx/pull/1424
