### ISSUE TITLE
How to suppress repaint of hidden Views?

### ISSUE THREAD

**Issue by ValeriusGC** [jonataslaw/getx#941]
_My excuse beforehand as it is not a bug, but i have no idea where to mention it._

When i go to another View and current one is being hidden it continues rebuild itself (why???) and affects performance despite of invisibility. So maybe there is some workaround or callback to process this situation?

Here is a code:
```
class PerformanceView extends StatelessWidget {
  @override
  Widget build(context) {
    final Controller c = Get.put(Controller());
    return Scaffold(
      appBar: AppBar(title: Obx(() => Text("Clicks: ${c.count}"))),
      body: Center(
        child: RaisedButton(
          child: Text("Go to Other"),
          onPressed: () => Get.to(
            OtherView(),
          ),
        ),
      ),
    );
  }
}

class OtherView extends StatelessWidget {
  final Controller c = Get.find();
  @override
  Widget build(context) {
    return Scaffold(body: Center(child: Text("${c.count}"),),);
  }
}

class Controller extends GetxController {
  Controller() {
    Timer.periodic(Duration(milliseconds: 100), (timer) {
      count.value = timer.tick;
    });
  }

  var count = 0.obs;
}

```

**Comment by jonataslaw** [comment]
This is the expected behavior in a stack framework (like Flutter).
It is precisely because the views below are being rebuilt that you can view the updated data when you pop it, since only the push reconstructs the screen, the pop does not call the build again.
This does not degrade performance, this is precisely a Flutter performance feature, since we will not have an entire screen being reconstructed when the last route leaves the stack.

**Comment by ValeriusGC** [comment]
It sounds good but screenshots with performance not so positive ))
![Screenshot from 2020-12-23 09-19-45](https://user-images.githubusercontent.com/3320861/102959021-2cde1300-4500-11eb-98c3-0d058a940334.png)
![Screenshot from 2020-12-23 09-19-59](https://user-images.githubusercontent.com/3320861/102959017-2bace600-4500-11eb-9fd5-fa4187f940e0.png)

**Comment by jonataslaw** [comment]
There are alternatives in the mobile world if you don't like working with Stacks, like the native android (I say this because the behavior mentioned is not related to Get, nor to Flutter, but to stack frameworks).
However, analyzing the graph I also don't see any performance problem in the screenshots, the project is running in debug (that only the VM alone already spends more than 45mb, and consumes much more CPU and GPU than in profile / mode release), I am sure that if it is run in profile / release mode, this would not be a problem even on a 2015 device. Also in the example you are updating the same variable in widgets of the same hierarchy, a single Obx in the Column widget would be appropriate for that situation.
