### ISSUE TITLE
I dont understand bindings

### ISSUE THREAD

**Issue by brianschardt** [jonataslaw/getx#945]
I have been using this package from the beginning, and have done a lot of research on bindings. 
What additional functionality do they actually provide?? I doesnt look like they really do anything that useful.

**Comment by jonataslaw** [comment]
Initially, Merry Christmas, I am answering this from my cell phone, but I hope it is possible to understand.
From the beginning: Bindings are just syntactic sugar so you have a place to start and inject your addictions. Under the table, dependencies are called when a new route enters the stack, and prepare all dependencies there that can be used later.
1- Why Bindings?
There are applications that have an infinite cycle. Facebook, Spotify, Twitter, Youtuber are examples of this. You can be on the home page, go to a profile, see a video/audio within a profile, click on comments, and then enter a profile you saw in the comments and start the cycle. If you ever do a Get.off, some page and its controllers will be removed from the stack and with them your controllers. When you enter that page again, the Bindings will be loaded, the controllers too, so that you remove everything from the memory when not needed, and allocate everything back when necessary. This gives greater control of dependency injection in addition to making explicit in the code which dependencies that particular route needs.
You can obviously ignore all of that, and insert your dependency with Get.put/Get.find() or the widget itself, but in that case, depending on the type of application you are designing, you may experience problems.
I personally worked on a social network that will be launched in January, and it had comments, audio comments, stories, messages, anonymous messages, groups, pages, the market, and basically everything that all social networks today have, but together.
I confess that the initial project was very difficult to read, as the dependencies were spread out over a few million lines of code.
We restructured everything for bindings and today if we want to know if dependency X is in a module Y, we simply open the bindings page and view it. Another advantage of bindings is: you can create an implementation for the real application, and an implementation for testing. You will not need to refactor anything in your application, just inject the Mock dependency instead of Impl, and this will make your job much easier.
Development bindings can mean a boring step, depending on the structure and how you use the framework, they are expendable, but for maintenance, in most situations they are simply fantastic. However it depends a lot on the type of application. An application that does not have many pages, and does not have an infinite cycle, can survive without problems without bindings. If there is another dependency injection feature, like InheritedWidget itself, there is no reason to use it. However, an application that has more than 80 dependencies, dispensing with its use can become a hell of a lot for future maintenance, especially if the team changes a lot.

Side note: an advantage not yet mentioned, since Flutter web is still in beta, is that in the next GetX update, Bindings will inherit the top level Bindings for dependency injection. So if you access the URL: products/eletronics/notebooks, it will automatically load the dependencies of products, and eletronics, and that on the web flutter is something that is really painful. If you access a direct URL of a page, which depends on dependencies on previous pages, this could be problematic in Flutter, and it will be something totally easy and automatic in version 3.25. Obviously Flutter web is still beta,

By the way, I just saw your email, as I was on vacation. 
Happy holidays.

**Comment by windy48** [comment]
Hi @jonataslaw, firstly thanks for your great work. I'm using bindings too, may I have a small question?
Regard to the "infinite cycle", how do you organize routes, bindings and controllers (with tags?)

I have a named route like:

  ```
GetPage(
      name: '/test',
      page: () => UserProfileDetail(),
      binding: UserProfileBinding(),
  )
```
  
  in UserProfileBinding: 
  
  `void dependencies() {
    Get.put(UserProfileController(), tag: Get.arguments);
  }`

 
and the situation was infinite cycle, I push: Get.tonamed('/profile', arguments: user.id) when user tap on any name or avatar
    
But ALL UserProfileControllers (with different id tags) is deleted once I do Get.back the first time, while only the last controller is expected to be deleted

![Screen Shot 2020-12-28 at 15 23 53](https://user-images.githubusercontent.com/6150523/103200834-f994ed00-4920-11eb-9914-6b6904610487.png)

Thanks again for your great work. Happy holidays.

**Comment by javiermrz** [comment]
First of all, great work with this package. I also want to say something about the bindings that I think is important to talk about. 

In cases where your using a more or less complex arquitecture (as in my case), there can be dependencies that depend on other dependencies that depend on other dependencies. (This is not a problem, it's just how the arquitecture is meant to work as it has some layers). So what I have is different files separated by "modules", in which I declare all dependencies that a module uses (User dependencies, Login dependencies, Core dependencies, etc.), and I call all those `Get.lazyPut()` when the application starts up.

## Problem
However, it is impossible to keep track of all of those nested dependencies in the bindings, and many times a "core" binding (used by many services) is removed automatically and breaks everything. Using Bindings is not a solution in this case, because even if I declare in the Bindings that my Controller uses XDependency and YDependency, these other dependencies use ZDependency, FooDependency and BarDependency, and so on. I believe someone else will find themselves in this same situation, so I want to try and make a bit of a debate here.

I have thoroughly read the documentation to see possible clean implementations for this problem. I can't call those in the Bindings though, because as I said, there is allways a dependency that is not directly included and breaks everything with an error similar to `Can't find X, please call Get.put() or Get.lazyPut()`.  

## Possible solution?
After reading the documentation, I don't really have a final solution that I have tested yet, but one idea that I have is declaring all dependencies at startup (as I am doing already) and maybe use `SmartManagement.keepFactory` so they are always available whenever they're needed.

What do you think about this idea? Any other possible solutions?

**Comment by eduardoflorence** [comment]
Hi @javiermrz, for a "core" service that is used in many other classes, you could make a class that extends from `GetxService` and not `GetxControler`. `GetxService` is not removed from memory automatically.

See: https://github.com/jonataslaw/getx#getxservice

**Comment by jonataslaw** [comment]
1- Use GetxServices for continuous dependencies. Every project (or almost all) will have dependencies that are maintained throughout the life cycle. GetxServices are created for this purpose.
If you want a dependency not to be removed, you can also use the permanent: true flag, and it will stay alive until a Get.delete (force: true) is called.
You can create a list of bindings, and insert the same Binding in each route in several routes, so it will be impossible to face the listed error, but this perhaps involves greater care about which dependencies each project uses.
2- Using central DI injection containers is not a bad thing, so much so that the framework allows you to do this, and you can do it. In the end it all depends on your architecture, your project, the way you are going to organize your dependencies, and Getx is not opinionated about your architecture. GetX is opinionated about things related to performance.

**Comment by javiermrz** [comment]
Thanks for your answer @eduardoflorence . I only use `GetXController` for services that I use directly from classes. The rest of the dependencies are simple classes that don't extend from any `GetX` functionality. Damn, I had searched into the documentation like crazy and dind't see the `GetXService` part, you have saved me a lot of hours, thank you very much :)

If you don't hear from me for a while, then that means it has worked like a charm.

**Comment by javiermrz** [comment]
@jonataslaw yep, completely true. Thanks for your help too! Maybe it would be useful to at least mention `GetXServices` in the `Dependency Injection` documentation, at least a link or something. When I read it, the "removed when not used" part sounds like it also re-instantiates the dependencies if needed again.

**Comment by brianschardt** [comment]
@jonataslaw I would love to setup a call with you where to ask questions and do a short term 2 week constulting project for us. Are you open?

**Comment by seekcx** [comment]
> Hi @jonataslaw, firstly thanks for your great work. I'm using bindings too, may I have a small question?
> Regard to the "infinite cycle", how do you organize routes, bindings and controllers (with tags?)
> 
> I have a named route like:
> 
> ```
> GetPage(
>     name: '/test',
>     page: () => UserProfileDetail(),
>     binding: UserProfileBinding(),
> )
> ```
> 
> in UserProfileBinding:
> 
> `void dependencies() { Get.put(UserProfileController(), tag: Get.arguments); }`
> 
> and the situation was infinite cycle, I push: Get.tonamed('/profile', arguments: user.id) when user tap on any name or avatar
> 
> But ALL UserProfileControllers (with different id tags) is deleted once I do Get.back the first time, while only the last controller is expected to be deleted
> 
> ![Screen Shot 2020-12-28 at 15 23 53](https://user-images.githubusercontent.com/6150523/103200834-f994ed00-4920-11eb-9914-6b6904610487.png)
> 
> Thanks again for your great work. Happy holidays.

Perhaps this is the problem that binding most needs to solve, not a design pattern.

**Comment by jonataslaw** [comment]
Since this issue is from last year, and apparently it has already been resolved, I am closing this
