### ISSUE TITLE
Changed behaviour of GetWidget in 3.24.0

### ISSUE THREAD

**Issue by saschaernst** [jonataslaw/getx#967]
As of 3.24.0 The controller in GetWidget is not available in the widget's constructor anymore

**Reproduction code**
```dart
// navigates to a page containing a list with individual GetWidget<TreatmentController> instances
Future<void> toOverview() => Get.off(
        const TherapyPage(PageType.therapy, Tr.therapy),
        binding: BindingsBuilder(
          () {
            Get.put(_getIt<TherapyController>());
            Get.create(() => _getIt<TreatmentController>());
          },
        ),
      );

// base class initializing the controller in its constructor
abstract class TherapyEntryWidget extends GetWidget<TreatmentController> {
  TherapyEntryWidget({
    @required String id,
  }) {
    controller.init(id);
  }

```

**To Reproduce**
I am displaying a list of independent GetWidgets in a list, each containing its own state (i.e. data, timers, etc). Until 3.23.1 I was able to access the controller in the widget's constructor and initialize it individually from there.

Since 3.24 the controller is only available after it ran its onInit, so in the widget's constructor it is still null.

**Expected behavior**
I would like to use the controller in the old way again or get a hint how to initialize the controller from a GetWidget from now on.

**Flutter Version:**
1.22 (latest stable)

**Getx Version:**
3.23.1 works fine, 3.24.0 fails

**Comment by jonataslaw** [comment]
You should not call functions in widget builders, this causes your widget to be marked as dirty, and each update to an ancestor will cause it to be rebuilt again in addition to being unable to be const.

However, if you really need this behavior, here is the code you can use to create the old GetWidget:

```dart
class _Wrapper<T> {
  T data;
}

abstract class OldGetWidget<T extends DisposableInterface>
    extends StatelessWidget {
  GetWidget({Key key}) : super(key: key);

  final _value = _Wrapper<T>();

  final String tag = null;

  T get controller {
    _value.data ??= GetInstance().find<T>(tag: tag);
    return _value.data;
  }

  @override
  Widget build(BuildContext context);
}
```

**Comment by saschaernst** [comment]
As I am not using the build method of the GetWidget, I am not sure to understand you correctly. Do you mean the parent's build method when creating the GetWidget?

**Comment by jonataslaw** [comment]
Just copy this into your code and use OldGetWidget instead of GetWidget.

**Comment by saschaernst** [comment]
I'd just like to understand how to have individually controlled widgets within a GetView to render complex data displays without hacking the framework. This seems to me like not too rare of a use case to prevent overbearing controllers on the page level using GetView. In other words: Shouldn't be something like the OldGetWidget still be available in the framework by default?

**Comment by jonataslaw** [comment]
His question was about a supposed behavior change, and as reported, there was no behavior change, the purpose of GetWidget is to deliver a single controller instance generated by Get.create, keeping this controller in a safe cache.

You can still (and should) pass the references you need from your widget to your controller, and this cannot be done in the constructor for reasons of performance and stability.

You can insert it in the method build (the build method of a GetWidget is only called once), or by passing the specific method it needs (I believe this is the most appropriate approach), and this is the safe way to do the that you wish.

In case you want to take a risk in a non-recommended approach, you can use this mentioned widget, but there is no guarantee that it will work and be stable. When the parent of this widget is rebuilt, for example, it will be rebuilt as well, the Controller will be discarded, and a new widget with a new controller will be created, which will result in data loss. So we have const constructors, and for that reason the class scope of a GetWidget, GetView is immutable. By doing Constructor(){} you are giving it up. For this reason, we do not recommend this approach involving widgets in any situation.
It is precisely to protect your application from breaking in the future or having undesirable behavior, that this is how it is, and if you heard an easier way to do it safely, it would certainly be done, but currently, with Flutter and dart in their current stage , this is how you should do this.

Since this is a question and has been answered, I am closing it.
